### ISSUE TITLE
[Feature Request] Hope print support __str__ protocol

### ISSUE THREAD

**Issue by Prodesire** [modularml/mojo#1026]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

Hope `print` support `__str__` protocol. For example, the following code can run normally:

```mojo
struct Foo:
    fn __init__(inout self):
        pass

    fn __str__(self) -> StringLiteral:
        return "foo"

fn main():
    print(Foo())
```

### What is your motivation for this change?

In python, print supports the `__str__` magic method, which is very convenient. I hope mojo can also support it.

**Comment by gryznar** [comment]
Mojo will support that for sure (as with other dunder methods). Currently this is not priority, cause it is only syntactic sugar.

**Comment by willghatch** [comment]
This is absolutely on the roadmap, though I can't say exactly when we plan to support it.

**Comment by JoeLoser** [comment]
A slight variant of your example works in v0.6.0:

```
struct Foo(Stringable):
    fn __init__(inout self):
        pass

    fn __str__(self) -> String:
        return "foo"

fn main():
    print(Foo())
```

Key things to point out:

- User-defined types right now need to explicitly declare conformance to the `Stringable` trait
- Your `__str__(self)` function must return a `String` type, not `StringLiteral`.  Our traits are exact-conformance right now, and we don't allow conversion on the return type to satisfy trait conformances at this time (akin to "convertible to").

Since this request is supported as of v0.6.0 when we launched traits initially, I'm going to close this issue.  Feel free to open a new request if you'd like to see the return type convertibility on the `Stringable` trait to be permitted, but our team already knows about these sort of things.
