### ISSUE TITLE
[FeatureRequest] Implement `len` on `object`

### ISSUE THREAD

**Issue by nullonesix** [modularml/mojo#1034]
### Bug description

```
fn main():
    def f(lst):
        return len(lst)
```
gets mojo: error: failed to parse the provided Mojo -- how do i use len inside a function in mojo?

### Steps to reproduce

- Include relevant code snippet or link to code that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- If using the Playground, name the pre-existing notebook that failed and the steps that led to failure.
- Include anything else that might help us debug the issue.

### System information

```shell
- What OS did you do install Mojo on ?
- Provide version information for Mojo by pasting the output of `mojo -v`
- Provide Modular CLI version by pasting the output of `modular -v`
```

**Comment by gryznar** [comment]
If am I not wrong it is not possible to combine declaring `def` function inside `fn`. What would you like to achieve?

**Comment by RickieBlaese** [comment]
`lst`'s type isn't specified (it's just a general `object`), so Mojo can't pick which overload of `len` to call. You can either specify the type of `lst` as some container type like [`DynamicVector[T]`](https://docs.modular.com/mojo/stdlib/utils/vector.html#dynamicvector) or [`StaticTuple[T]`](https://docs.modular.com/mojo/stdlib/utils/static_tuple.html#statictuple) which `len` does have overloads for.

I think you might be looking for 2 things.
1. Dynamic typing, where you provide no information about the type of `lst`. This is not possible in pure Mojo at the moment, and also probably not the best solution for this case. You indeed do know something about `lst`, i.e. that it is a container type for storing a number of objects, and that it has to have a length.
2. Traits, which allow you to describe a type through precisely defined building blocks. You might specify that `lst` has to satisfy a trait that indicates it has a length and you can get that length through some function. [This](https://docs.rs/len-trait/latest/len_trait/len/trait.Len.html) is the perfect example from Rust. Traits do not exist in Mojo at the moment, but are being worked on, since they're pretty useful. See the [roadmap](https://docs.modular.com/mojo/roadmap.html#protocols-traits) for some more on this.

In the meantime, you'll have to manually confine this function to only working for some types. If you wanted this work for any `DynamicVector[T]`, you might write it like this:
```
from utils.vector import DynamicVector

fn main():
    fn f[T: AnyType](lst: DynamicVector[T]) -> Int:
        return len(lst)

    # And then you could use it like this:
    var v = DynamicVector[Int]()
    v.push_back(1)
    v.push_back(2)
    print(f(v))
```

**Comment by willghatch** [comment]
The comment from @RickieBlaese is correct.  Traits are a fairly high priority in the roadmap, we will have them before too long.  Since there's nothing really actionable about this issue right now, I'm going to go ahead and close it.
