### ISSUE TITLE
[Docs] Document translate to Chinese

### ISSUE THREAD

**Issue by HuckOps** [modularml/mojo#1041]
### Where is the problem?

Don't have Chinese document

### What can we do better?

This is my own translated Mojo document, and I hope it can be included in the official document to help developers in China

https://mojo.huckops.xyz/

I will gradually improve document translation recently

**Comment by gryznar** [comment]
Nice! Keep in mind, that Mojo is faaar away from being mature (and even stable it its API), so this could last long time to introduce translations

**Comment by HuckOps** [comment]
> Nice! Keep in mind, that Mojo is faaar away from being mature (and even stable it its API), so this could last long time to introduce translations

Ok，this is the repo of the translated document https://github.com/HuckOps/mojo-docs-zh， I hope more and more people to join us.

**Comment by scottamain** [comment]
Thanks for sharing @HuckOps! But it's true that localization is low priority right now because the language, APIs, and documentation are changing rapidly and will be for the foreseeable future. But we welcome you to reuse the published documentation for your translations and share them with the community. Thanks for sharing your enthusiasm in Mojo! 🔥
