### ISSUE TITLE
[BUG]: Importing the numpy C-extensions failed. (Macbook Pro M1)

### ISSUE THREAD

**Issue by theopomies** [modularml/mojo#1085]
### Bug description

Running the command `mojo matmul.mojo` results in the following error output:
$ mojo matmul.mojo       
Unhandled exception caught during execution: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.10 from "/Users/theopomies/.modular/pkg/packages.modular.com_mojo/bin/mojo"
  * The NumPy version is: "1.24.2"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: cannot import name 'Sequence' from 'collections' (/opt/homebrew/anaconda3/lib/python3.10/collections/__init__.py)

mojo: error: execution exited with a non-zero result: 1

### Steps to reproduce

- No specific steps, just installed mojo beta 0.4.0 on my Mbp M1 and tried the first example from the docs.

### System information

```shell
- What OS did you do install Mojo on ? Apple M1 Pro, macOS Sonoma Version 14.1 (23B73)
- Provide version information for Mojo by pasting the output of `mojo -v`: mojo 0.4.0 (9e33b013)
- Provide Modular CLI version by pasting the output of `modular -v`: modular 0.2.1 (5144fffe)
```

**Comment by PythonAlchemist** [comment]
+ 1 but from numpy on Apple M1

Error: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.11 from "/Users/christophersinger/.modular/pkg/packages.modular.com_mojo/lib/mojo-repl-entry-point"
  * The NumPy version is: "1.23.5"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'

**Comment by jackos** [comment]
Hi @PythonAlchemist and @theopomies the easiest way to fix this for both of you will be to install conda if you don't have it following these steps: https://docs.conda.io/projects/miniconda/en/latest/#quick-command-line-install

make sure to init:
```
~/miniconda3/bin/conda init --all
```
Restart your shell and then run these commands:
```
export MOJO_PYTHON_LIBRARY="$(find $CONDA_PREFIX/lib -iname 'libpython*.[s,d]*' | sort -r | head -n 1)"
echo "export MOJO_PYTHON_LIBRARY=$MOJO_PYTHON_LIBRARY" >> ~/.zshrc
conda install numpy 
```
And try again

**Comment by theopomies** [comment]
Hi @jackos, thanks for this reply, it worked on my end

I already had conda and numpy installed but repeating the steps from https://docs.conda.io/projects/miniconda/en/latest/#quick-command-line-install and the commands you shared fixed the issue.

**Comment by PythonAlchemist** [comment]
@jackos same for me, thank you!

**Comment by joakimeriksson** [comment]
Will it make a difference with miniconda instead of conda?

**Comment by jackos** [comment]
@joakimeriksson no, all good to use normal `conda`
