### ISSUE TITLE
[Dev Console]: web-based Mojo Playground doesn’t show any code error

### ISSUE THREAD

**Issue by AmitXShukla** [modularml/mojo#1154]
### Issue description

I find web-based [Mojo Playground](https://docs.modular.com/mojo/manual/get-started/#develop-in-the-mojo-playground) very useful tool to experiment and learn. However Notebooks doesn’t show any code error or code completion,

### Steps to reproduce

Let x = 2
x = 3

shows random parse error instead of actual code error.

**Comment by kazurayam** [comment]
I have got a similar insident in the [Mojo Playground]. See the following:

<img width="1416" alt="Screenshot 2023-11-15 at 17 22 55" src="https://github.com/modularml/mojo/assets/4467417/e4b5859d-9a20-4e15-9040-b3fdc017c4df">

I am aware of my mistake in the code (I should write`from python` instead of `from Python`).

However, I hope the Mojo Playground to give us more adequate diagnostics. I only got a message `expression failed to parse (no further compiler diagnostics)` without any useful diagnostics.

I tried the same code in VSCode. I saw better diagnostics.

<img width="1233" alt="Screenshot 2023-11-15 at 17 23 28" src="https://github.com/modularml/mojo/assets/4467417/46deb2a9-2201-48a2-9968-921916da786d">

**Comment by kazurayam** [comment]
I have got a similar incident in the web based [Mojo Playground](https://playground.modular.com/user/kazuaki.urayama@gmail.com/lab/tree/EuclideanNorm.ipynb). See the following:

<img width="1416" alt="Screenshot 2023-11-15 at 17 22 55" src="https://github.com/modularml/mojo/assets/4467417/e4b5859d-9a20-4e15-9040-b3fdc017c4df">

I am aware of my mistake in the code (I should write`from python` instead of `from Python`).

However, I hope the Mojo Playground to give us more adequate diagnostics. I only got a message `expression failed to parse (no further compiler diagnostics)` without any useful diagnostics.

I tried the same code in VSCode. I saw better diagnostics.

<img width="1233" alt="Screenshot 2023-11-15 at 17 23 28" src="https://github.com/modularml/mojo/assets/4467417/46deb2a9-2201-48a2-9968-921916da786d">

**Comment by ematejska** [comment]
Closing this out because the Jupyter based mojo playground was deprected.
