### ISSUE TITLE
accelerate the promotion of Mojo

### ISSUE THREAD

**Issue by sosocom** [modularml/mojo#1190]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

what's the mojo use for? is there any application has been pulished developed by mojo?  or is there game or product? More use cases will accelerate the promotion of Mojo.
Here is some example: Mojo to write a web api? or write a base AI example ..

### What is your motivation for this change?

accelerate the promotion of Mojo.

### Any other details?

hope to get some course on this

**Comment by rarebreed** [comment]
I actually am of the opinion that Mojo may have been released too early.  While I think it's okay to put into the hands of early adopters to work out some issues (ie, see all the installer issues), I am actually afraid Mojo may have been promoted too early.

I believe from reading the various discussions and issues that there are two basic kinds of people interested in mojo:

1. The low level machine learning folks who are good with C/C++/rust who write (math) kernels, BLAS, GEMM or other math
2. People who want a "better" python

For the first group, I think it's probably okay to promote and advertise more to them.  Mojo is currently an unsafe language like C/C++, so it doesn't faze this group to work with low level pointers.  However,  once Mojo gets lifetimes and full ownership semantics, this may be a turn off to C/C++ users who are not accustomed to this language feature  (though it should delight rust users).  But for the 2nd group, I don't think it's a good idea to promote mojo for them yet.  

Reading many of the issues and seeing a lot of discussion posts, I feel like a fair number of people are not aware of how Alpha mojo is.  There is a lot of work that needs to be done to make mojo friendly to the masses.   I am afraid many will try mojo and then feel frustrated at how much is still missing, especially the 2nd group of people. 

Since mojo source code is not open sourced yet, what would the benefit of  promoting Mojo even more be?  At my work place, while I am not in any of the AI groups, I am on the Analytics side of things.  So I use polars, duckdb, pyarrow, spark, etc.  We're a Java shop mostly, but I am trying to get them more into the python side of things, like eg ray.  I have mentioned mojo to many people at my company, but I also warned them that Mojo is very very alpha, and will change radically as new features are implemented (especially lifetimes/ownership).  I basically just wanted others to keep an eye on it.  About the only comment I have gotten about mojo is: "we'll see if they can fulfill on their promises".

So I would actually rather wait to see mojo fleshed out a bit more before really trying to promote mojo even more.  I would suggest keeping the current profile mojo has until the following have been done:

- Release lifetimes and ownership, because that's going to be a huge change to the language
- Minimum stdlib to include more data types, more IO
- Traits/Typeclasses to implement Iterators
    - I strongly feel this should not be named Protocols, since Python already has Protocols for subtyping 
- Algebraic Data Types for Maybe/Option/Result/Either types instead of requiring Exception Handling
- Release for Arm64 on linux (and more distros, I think x86_64 on macs can wait, since Apple has abandoned it)

**Comment by rarebreed** [comment]
I forgot to add that once more of mojo has been implemented, I'd like to write a course or book on mojo.  One of the biggest things that helped me learn rust was the free and excellent rust book.  But one thing I think I would do differently is build a small real world project along the way.

**Comment by gryznar** [comment]
Totally agree with @rarebreed. Mojo is very, very promising, but it is still in alpha. IMHO the promotion should not start before 1.0 which I hope to have at least traits, lifetime and basic stuff like dict / set / list implemented.

**Comment by ematejska** [comment]
Indeed,  Mojo is still in the early phases of development and we're still working on some major features as described in the roadmap (https://docs.modular.com/mojo/roadmap.html).  Stay tuned one place we're highlighting progress in our newsletters (https://www.modular.com/newsletters).  I'm going to close this issue because it's not a very specific and this kind of discussions might be better for our discord channels or Github discussions.
