### ISSUE TITLE
Factorial should specify constraints

### ISSUE THREAD

**Issue by hoxha-saber** [modularml/mojo#1254]
### Where is the problem?

https://docs.modular.com/mojo/stdlib/math/math.html#factorial

### What can we do better?

In general, the factorial function is only defined for non negative integers. However, the docs don't place any constraints on the input. Is the mojo implementation only working for non negative integers?

### Anything else?

Also on a somewhat related note, if input constraints are violated will the mojo library trigger a runtime assertion or silently fail? For example, gcd(-2, -4) returns -2 which is incorrect but because I'm violating the constraint of "inputs must be non negative" is undefined behavior so it makes sense why it's incorrect.

**Comment by arjunchainani** [comment]
From what I see, the Mojo implementation only works **correctly** for non-negative integers. It gives some weird outputs when I try passing in negative integers: 

![image](https://github.com/modularml/mojo/assets/109640014/d75a2b78-2b6a-4664-b7f0-0d424eafc00f)

The easiest solution would probably be to add constraints to the function and just raise an explicit error when attempting negative factorials.


For the GCD issue, technically the result you get from gcd(-2, -4) should still be positive 2, since that is the largest factor (negative factors will always inherently be smaller than their positive counterparts, and so you technically can take the GCD of a negative number but your answer should be positive). 

So I think it might actually be better to remove the constraints for the GCD function and just make sure it works with negative numbers.

**Comment by hoxha-saber** [comment]
> From what I see, the Mojo implementation only works **correctly** for non-negative integers. It gives some weird outputs when I try passing in negative integers: 
> 
> ![image](https://github.com/modularml/mojo/assets/109640014/d75a2b78-2b6a-4664-b7f0-0d424eafc00f)
> 
> The easiest solution would probably be to add constraints to the function and just raise an explicit error when attempting negative factorials.
> 
> 
> For the GCD issue, technically the result you get from gcd(-2, -4) should still be positive 2, since that is the largest factor (negative factors will always inherently be smaller than their positive counterparts, and so you technically can take the GCD of a negative number but your answer should be positive). 
> 
> So I think it might actually be better to remove the constraints for the GCD function and just make sure it works with negative numbers.

Yes I was mainly wondering that since factorial is not working correctly, they should specify in the docs that only non negative integers are permitted.

Also as you mention gcd(-2, -4) is incorrect in mojo but we aren't using it correctly so it's not the library's fault.

**Comment by scottamain** [comment]
@JoeLoser can you please take a look at this.
