### ISSUE TITLE
[BUG]: Aliasing function with default parameters doesn't work

### ISSUE THREAD

**Issue by soraros** [modularml/mojo#1314]
### Bug description

As title. Found by @helehex.

### Steps to reproduce

The following code type checks but all the instantiation in `main` doesn't work. Compiler is not bothered with made up name (`X`) as well.
```mojo
fn f[A: Int, a: Int = A]():
  print(A, a)

alias f1 = f[1, 10]

fn main():
  alias g = f1[10, 20, X=30]
  g()
  let h = f1[10, X=20]
  h()
  let i = f1[A=10]
  i()
```

### System information

```shell
Mojo 0.5.0 on Docker, Intel Mac
```

**Comment by Mogball** [comment]
```
/tmp/test.mojo:9:17: error: unknown keyword parameter: 'X'
    alias g = f1[10, 20, X=30]
                ^
/tmp/test.mojo:11:15: error: unknown keyword parameter: 'X'
    let h = f1[10, X=20]
              ^
/tmp/test.mojo:13:15: error: unknown keyword parameter: 'A'
    let i = f1[A=10]
              ^
```

**Comment by soraros** [comment]
@Mogball Isn't this error message kinda missing the point? Shouldn't `f1` be a fully bound alias, and can't accept any more parameter?

**Comment by Mogball** [comment]
Yeah i think the priority of the error messages here is wrong. Will change that.

**Comment by laszlokindrat** [comment]
@soraros Thanks for filing the ticket! I had a discussion with @Mogball about the precedence of different overload resolution failures. The rationale for why keyword-related errors are high precedence is that keyword-only arguments and keyword operands are a very specific way to expect/provide values in function calls. Because of this, related errors tend to be very specific and actionable, and so these should have  high priority. Moreover, the cause of keyword-related candidate failures are often intended by the user (i.e. not wanting to use a particular overload), or the result of a clear mistake they can fix immediately.

The precedence from Python is also consistent with this:
```python
def foo(a, b, d): pass

# TypeError: foo() got an unexpected keyword argument 'x'
foo(1, 2, 3, 4, 5, x=6)
```
All this being said, it would probably be useful to emit a note along with the error, pointing out that `f1` is fully bound, or maybe not permitting the subscript operation on `f1` at all.

**Comment by laszlokindrat** [comment]
Action item filed in https://github.com/modularml/mojo/issues/1799.
