### ISSUE TITLE
[Feature Request] lifetime like rust

### ISSUE THREAD

**Issue by mojo-for-ai** [modularml/mojo#1343]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

I want to support lifetime in Mojo like Rust. We need to support this in Mojo due to its extreme importance

### What is your motivation for this change?

Make Mojo safer, more advanced and more modern

**Comment by Sharktheone** [comment]
Lifetimes are already on the roadmap: See the section [Ownership and Lifetimes](https://docs.modular.com/mojo/roadmap.html#ownership-and-lifetimes) and [proposals/lifetimes-and-provenance.md](https://github.com/modularml/mojo/blob/main/proposals/lifetimes-and-provenance.md)

**Comment by rarebreed** [comment]
> I am thinking that using <> angle brackets for lifetime would be more distinct. Using square and parentheses kind of overloads concepts and causes confusion while reading code.

I have programmed in rust about 5 years, but I think having angle brackets is not a good idea.  Why?Python already uses `[T]` in python 3.12 for generics thanks to [PEP-695](https://peps.python.org/pep-0695/) (and is why [mojo's parameterized types](https://docs.modular.com/mojo/programming-manual.html#defining-parameterized-types-and-functions) follow it as well). Afterall, a lifetime specifier is in a sense, another kind of "generic".

It would be even more confusing in my opinion, to have `<>` for lifetimes, and then `[]` for other generic parameters.  Also, python already uses `[]` to specify type annotations like `list[str]`.  Many pythonistas used to using `[]` to specify the generic type param will be even more confused if they have to use one block form for generic types, and another block form for lifetimes.

All this being said, you could have something like below (taken from the [proposal for references and lifetimes](https://github.com/modularml/mojo/blob/main/proposals/lifetimes-and-provenance.md)):

```
fn example[life: Lifetime](
    cond: Bool,
    x: ref<life> String,
    y: ref<life> String
):
    # Late initialized local borrow with explicit lifetime
    let str_ref: ref<life> String

    if cond:
        str_ref = x
    else:
      	str_ref = y
    print(str_ref)
```

Frankly, I would prefer this:

```
    x: ref[life] String,
    y: ref[life] String
```

as I will have less things to keep track in my head because it uses the same block form for both and is consistent with python syntax (eg `ref[Lifetime]`)

IMHO, keeping the mojo syntax as close as possible to python is a good strategy, because it will be less intimidating for pythonistas to learn.  I love rust, but it's been very frustrating trying to get coworkers interested in it because it is so dissimilar to anything they have done before.  Lifetimes are already complicated enough (so I hope mojo can do even more lifetime ellision than rust can).  Indeed, I want mojo to be successful because I think piggy backing off python syntax will be less intimidating to learn.

**Comment by rarebreed** [comment]
Come to think of it, I'd prefer this syntax

```
    x: ref[life, String],
    y: ref[life, String],
```

Then it's more consistent with other python syntax.  It makes it look like `ref` is something like

```
class ref[life: Lifetime, T]:
    ...
```

**Comment by ivellapillil** [comment]
```
fn example<life>[T](
    cond: Bool,
    x: ref<life> String,
    y: ref<life> String,
    z: T
):
    # Late initialized local borrow with explicit lifetime
    let str_ref: ref<life> String

    if cond:
        str_ref = x
    else:
      	str_ref = y
    print(str_ref)
    ...

```

Is not too bad for me.

**Comment by ivellapillil** [comment]
To further add, lifetime is another dimension orthogonal to types. Having it flattened in the same syntactic construct would be problematic...

**Comment by rarebreed** [comment]
> IMHO lifetime is not really a type. It is more akin to a tag which is tracked by the compiler. You can't create a variable nor field with a lifetime as its **type**. So putting it same as generics is quite confusing at least to me.
> 
> I think of lifetime as a tag similar but not the same as effect tags. So if we ever have effect tracking in Mojo, I think angle brackets would be best to identify such tags..
> 
> Our code would be littered with the `x: Lifetime` and it could never be anything other than `Lifetime` "type".
> 
> This duplication is already indicating that we don't have the concept exactly nailed.
> 
> `<x>` would be clear enough and visible enough. We can pass multiple lifetime parameters with <x, y, z>. Visually it is easier to trace all cases where the lifetimes are parameterized.
> 
> Just my 2 cents.

Even in rust, in a sense they are, although perhaps it might be easier to think about them as a kind of trait.

Rust syntax is a bit confusing for new comers precisely because it's not clear what `'a` really is.  It looks very similar where it used, both in the `<>` like a type parameter, and also right before the `&` symbol.  I like the approach mojo is taking by making it more verbose, but also making it more clear that there is a `Lifetime` type, and a `ref` value (that takes a Lifetime type).

In rust, I read the below code as "foo takes type parameters of Lifetime `a` and a `T` which supports the `Display` trait. The argument to `foo` takes a `Vec` whose elements are a Reference with a lifetime `'a`  to a type `T`.".  In other words, I mentally replaced the `'` sigil as "Lifetime type", and the `&` sigil as "Reference type".

```rust
fn foo<'a, T: Display>(container: Vec<&'a T>)  {
    for i in container.iter() {
        println!("{}", i);
    }
}
```

Here, __Lifetime a__ can be thought of as a type.  Notice I translate it in my head as "_Lifetime a_" and not "_Lifetime **of** a_".  It's a subtle distinction, but it helps me understand that `a` only makes sense in combination with `Lifetime`. Imagine if rust had used mojo's syntax

```rust
fn foo<a: Lifetime, T: Display>(container: Vec<Reference<a, T>>)
    where T: Display {
    for i in container.iter() {
        println!("{}", i);
    }
}
```

Here now, we see the distinction more clearly that a lifetime is actually kind of like a trait, and that the `&` sigil is really syntactic sugar for a Reference that takes a Lifetime (so for example, we could have `Vec<Reference<str>>`) and whatever the type is that it is referencing.  What gets confusing in rust is that the `'` and `&` sigils hides what the meanings are.  So in some ways, I like how mojo is making this more explicit than rust.

I wish rust had been more explicit, and done what mojo is doing.

```
foo[life: Lifetime]():
    x: ref[life] String
```
Makes this much more clear that a `ref` takes a Lifetime type, so it clearly distinguishes `Lifetime` vs `ref` unlike rust

**Comment by rarebreed** [comment]
> To further add, lifetime is another dimension orthogonal to types. Having it flattened in the same syntactic construct would be problematic...

As I showed in my other post, I kind of think of lifetimes somewhat like a trait.  So I can see where you are coming from that lifetimes are like tags.  I personally tend to think of them like traits that constrain a type.  Also, rust has [lifetime subtyping and variance](https://doc.rust-lang.org/nomicon/subtyping.html) which also makes me think of types and traits (eg, 'a might be a lifetime subtype of 'b, meaning that 'b lives at least as long as 'a, so you can use a 'b lifetime where an 'a lifetime is expected/required).

As for being orthogonal, I had to think about that.  If it was truly orthogonal, the new dimension would have no effect on the other dimensions.  For example, you could give me coordinates for translation in a 3d system, and I can make it work in a 2d system merely by ignoring the z-dimension and the projection will be valid.  

But I don't think lifetimes work that way.  The compiler can't just "ignore" the lifetime "dimension".  The compiler will reject invalid lifetimes.

**Comment by rarebreed** [comment]
> @rarebreed I think rust got the `'a`, `'b`, etc. notation from OCaml, which means alpha, beta etc and it's easy to type on a keyboard.

I wouldn't be surprised since rust's initial compiler was written in OCaml.

I've tried teaching rust to several people, and lifetime references and ownership are easily the hardest concepts for people to understand.  The terse syntax doesn't help I think, so I don't mind if mojo is a bit more verbose.  The more I think about it, the more I like this syntax

```
foo[life: Lifetime]():
    x: ref[life, String]
```
It's similar to how python currently is (eg, `ref[Lifetime, T]: TypeAlias = tuple[Lifetime, T]`) so I don't have to remember to use `<>` in one place and `[]` for the other.  It also doesn't have unusual syntactical form like `x: ref[life] String`.  

I think there are two ways to think about a reference. You can think about as a higher kinded type that takes two type params, or you can think of it as a modifier or constraint of just one type.

I kind of feel like a Reference is (or could be) a higher kinded type.  So for example, `ref[life]` is really itself a type constructor that takes one more argument: the type it is pointing to.  However, it's also not exactly a higher kinded type if all you care about is lifetime tracking.  Because the compiler doesn't need to know the referrant type to determine validity...just the lifetime itself.  For the compiler's purpose of lifetime validity checking, `ref[life]` is a "complete" type (or if you think of it as being complete, a kind of marker trait that modifies a type).

That's why I can empathize with thinking of a lifetime as just a tag or dimension.  Ultimately, a reference really has two parts: the lifetime, and what it's pointing to.  It needs the lifetime for liveness checking, and it also needs to know what it is pointing to so the compiler knows the size.  The syntax `x: ref[life] String` makes it look (to me) like a `ref` only takes one type param, and it's doing something funky with String.  A modifier?  I think perhaps this syntax was chosen because for "aliveness" checking, that's all a `ref` needs...the lifetime type.

But that's really not complete.  The syntax form below reads just like any other type as "x is a Reference with type params life and String".  In fact, maybe even this is better:

```
x: Ref[life, String]
```
So that uppercase Ref appears more like a type rather than specialized syntax.

**Comment by ivellapillil** [comment]
> I personally tend to think of them like traits that constrain a type. Also, rust has [lifetime subtyping and variance](https://doc.rust-lang.org/nomicon/subtyping.html) which also makes me think of types and traits (eg, 'a might be a lifetime subtype of 'b, meaning that 'b lives at least as long as 'a, so you can use a 'b lifetime where an 'a lifetime is expected/required).

I had missed out the part that lifetime conceptually has some kind of subtyping. In this sense it is not a pure tag.

>  You can think about it as a higher kinded type that takes two type params, or you can think of it as a modifier or constraint of just one type.

This is also another way to look at it.

I would like to thank both of you for taking the time to explain your positions. I think given the arguments it makes send to consider Lifetime as a type, then it is natural to use the generic syntax...

**Comment by lattner** [comment]
This is already on the roadmap.  The discussion is great, but please bring it over to the existing thread here: https://github.com/modularml/mojo/discussions/338
