### ISSUE TITLE
[BUG]: simd integral `//` always returns zero with negative operand

### ISSUE THREAD

**Issue by helehex** [modularml/mojo#1464]
### Bug description

floor divide always return zero if any of the operands are negative

### Steps to reproduce

```py
fn main():
    let a: Scalar[DType.int64] = -4
    let b: Scalar[DType.int64] = -2

    print(a//b)  # prints 0
    print(a/b)   # prints 2
    # print(-4//b) # error, recursive call
```

### System information

```shell
Host Information
  ================

  Target Triple: x86_64-unknown-linux
  CPU: skylake
  CPU Features: 64bit, adx, aes, avx, avx2, bmi, bmi2, clflushopt, cmov, crc32, cx16, cx8, f16c, fma, fsgsbase, fxsr, invpcid, lzcnt, mmx, movbe, pclmul, popcnt, prfchw, rdrnd, rdseed, rtm, sahf, sgx, sse, sse2, sse3, sse4.1, sse4.2, ssse3, x87, xsave, xsavec, xsaveopt, xsaves

mojo 0.6.0 (d55c0025)

modular 0.2.2 (95d42445)
```

**Comment by JoeLoser** [comment]
Thanks for filing the bug report.  I confirmed the repro and it's indeed a bug.  BTW, in the third example, the function (`__floordiv__`) actually got removed in v0.6.1 release (coming next week) due to the recursive call (someone else ran into this internally while doing something else).  We'll fix that separately and revive that function.

**Comment by bgreni** [comment]
@JoeLoser  Testing on `mojo 2024.5.622 (d9dc4c21)` and this appears to have been resolved

**Comment by helehex** [comment]
yup looks good to me

**Comment by JoeLoser** [comment]
Great, thanks for closing it! I haven't looked closely, but the community has been filling in a lot of missing methods and fixing them, so I'm sure this was one of them 🎉🎉🎉
