### ISSUE TITLE
[Docs] Literals: Why would one want to use it/why are they there?

### ISSUE THREAD

**Issue by PP6464** [modularml/mojo#1510]
### Where is the problem?

n/a

### What can we do better?

I think there needs to be clarification as to why there is listliteral, stringliteral etc. types, and why they should be used (or not), as I could not find a single piece of documentation that explained this

**Comment by gryznar** [comment]
Good point! +1 for clarifying in docs!

**Comment by arthurevans** [comment]
Short term, I think we can clarify the API docs for these types.  (Longer term, the manual should include a section on types.)

Literal expressions are constant values that can appear in code. For example:

```
var s = "A string literal"
var f = 3.14  # A float literal
var i = 5       # An integer literal
var l = ["one", "two", "three"]   # A list literal
```

Mojo has types to represent these literals, like `StringLiteral`, `FloatLiteral`, and so on. When you do:

```
var s: String = "the string literal."
```

Mojo creates a `StringLiteral` (value: "the string literal"). Then, because `s` is type `String`, it calls the `String` constructor method that takes a `StringLiteral`. (Currently that's the 4th overload for its [`__init__()` method](https://docs.modular.com/mojo/stdlib/builtin/string.html#init__).) So the string literal has a very short life: it's just there to initialize the String.

The literal types have limited, mostly read-only APIs because they're generally only used for initializing other types. So you might use these types when writing constructors (for example, you might have one constructor that takes a `String`, and another that takes a `StringLiteral`).

In the case of `ListLiteral`, people sometimes use it because Mojo currently has very limited options for storing a list of heterogeneous values, so `ListLiteral` can be useful even though it only provides an immutable list.

**Comment by PP6464** [comment]
Thanks for clarifying 👍, and I hope in the longer term there is a list struct for heterogenous elements
