### ISSUE TITLE
[Docs] Improperly renamed function in manual for parameters

### ISSUE THREAD

**Issue by gryznar** [modularml/mojo#1544]
### Where is the problem?

https://docs.modular.com/mojo/manual/parameters/#parameterized-structs

### What can we do better?

![image](https://github.com/modularml/mojo/assets/90425096/047fe1c6-a814-4823-862b-277444e726fc)
Function `speak()` was improperly renamed to `foo()`

**Comment by thphuc** [comment]
@scottamain @arthurevans I am going to fix this. Which name do you prefer? "speak" or "foo"?
Personally, I think "foo" makes more sense because we also have "bar"

**Comment by arthurevans** [comment]
Hi @thphuc ... It should be `speak` here, because it refers back to the previous example. The text suggests that we're updating the previous example (`speak[Int, String]()`).  (Ideally we'd rename `Bar` as well, but I don't have any great suggestions at the moment and it's not necessary to fix this bug.)

(If you'd like to make a fix here, both these examples should probably use `String` instead of `StringLiteral` for the `msg` parameter, too.)

In general I'm trying to rework examples to replace names like `foo()` and `Bar` and variable names like `a` with more descriptive names, but it's a slow process.

**Comment by thphuc** [comment]
Hi @arthurevans Thanks for your feedback. 
(I'm learning Mojo here) I'm happy to refactor the examples/code if I have a chance.
