### ISSUE TITLE
[Docs] Document try-except semantics and the `raises` keyword

### ISSUE THREAD

**Issue by jacksonwb** [modularml/mojo#1611]
### Where is the problem?

https://docs.modular.com/mojo/manual/functions.html

### What can we do better?

There does not appear to be any section in the documentation that describes try-except semantics and Exception types and how this functions across `def` and `fn` functions and methods.

Additionally the raises keyword is mentioned, and its behavior is implied but does not seem to be explicitly defined

**Comment by arthurevans** [comment]
Yep, we currently don't have a section on error handling, and we need one. In theory this is one of the areas we've left for later documentation because it's similar to Python. In practice, needing to declare when a function `raises` and the fact that we use `Error` instead of `Exception` (as described in the [Roadmap](https://docs.modular.com/mojo/roadmap.html#exception-is-actually-called-error)) is different enough that we might need to document this sooner.
