### ISSUE TITLE
[BUG]: Memory access issue in a parallelized function when accessing a dynamic vector

### ISSUE THREAD

**Issue by andresnowak** [modularml/mojo#1634]
### Bug description

When accessing a dynamic vector inside a parallelized function we get a segmentation fault or what seems to be access to incorrect parts of memory

## Code:
```py
from algorithm import parallelize

fn main():
    var h = DynamicVector[Int]()
    for i in range(10):
        h.push_back(i)

    @parameter
    fn parallel_access(i: Int):
        print(h[i])
        print(h[0])
    
    parallelize[parallel_access](10)
```

## Output:
```
9700550137077554932
86
7-5442414679759695298



97005501370775

9700550137077597005501370775

97005501370775970055013707759700550137077597005501370775


9700550137077597005501370775

97005501370775



```

### System information

```shell
- What OS did you do install Mojo on ? PopOs
- Provide version information for Mojo by pasting the output of `mojo -v`: mojo 0.6.1 (876ded2e)
- Provide Modular CLI version by pasting the output of `modular -v`: modular 0.3.1 (589ce200)
```

**Comment by mikowals** [comment]
I think `h` is getting destroyed before your parallel loop runs.  I made a slightly different reproducer just because printing output in parallel is tough to read and reason about.

You can still see the junk output if you remove the last line.  If you use `h` after the call to `parallelize` in your example you get a group of the digits 0-9 and ten 0s after that.  So I think it is fixed in your example also.  I think not keeping `h` alive in a function that captures it is a known bug that will be fixed at some point after correct lifetime support.

```
from algorithm import parallelize

fn main():
    var h = DynamicVector[Int]()
    var a = DynamicVector[Int]()
    a.resize(10, 0)

    for i in range(10):
        h.push_back(i)
        print("h[", i, "] = ", h[i])

    @parameter
    fn parallel_access(i: Int):
        a[i] = h[i]

    parallelize[parallel_access](10)

    for i in range(10):
        print("a[", i, "] = ", a[i])
    _ = (h,) # keep h from being cleaned up
```

**Comment by andresnowak** [comment]
How couldn't I think about that. Yes that was the problem, thank you for your help. I will close this issue now.
