### ISSUE TITLE
[Docs] Clarify the difference between "parametric" and "generic"

### ISSUE THREAD

**Issue by nmsmith** [modularml/mojo#1636]
### Where is the problem?

https://docs.modular.com/mojo/

### What can we do better?

The Mojo docs alternate between using the terms "generic" and "parametric" when discussing functions and structs that have parameters.

To the best of my knowledge, there is no real distinction between these terms in the context of Mojo. Every "generic" thing is just a thing that has parameters. Therefore, would it make sense to do a "find all" over the docs, and replace "generic" with "parametric"? This would eliminate one piece of jargon from the Mojo lexicon.

The Python community uses the term "generics" for their use of `[]` within type hints, so we would probably also need to add a small note somewhere in the docs that clarifies the terminological change in Mojo.

I'm happy to submit a pull request if Modular thinks this would be appropriate.

**Comment by arthurevans** [comment]
I think at this point we only use the term "generic" a few places in the traits doc and the parameters doc.

It's not a synonym for parametric. It means the same thing that it means in most statically-typed languages: a type or function that can contain (or act on) different types of objects. `DynamicVector` is generic because it can hold a vector of `Int`, `Float64`, or `String` values (among others). Whereas [`unroll()`](https://docs.modular.com/mojo/stdlib/algorithm/functional.html#unroll) is parametric, but not generic. The concepts are related because all generic types and functions are parametric.

- Parameters are compile-time values. 
- To write generics in Mojo, you use parameters to specify types, so you can write code that's generic over a set of types (like `DynamicVector`) which are specialized at compile time to concrete types (like `DynamicVector[Int]`).

Right now support for generics in Mojo is very new and in flux. Writing a generic struct like `DynamicVector` usually requires  a bunch of specialized knowledge and writing some MLIR by hand. We'll add more details on generics in an upcoming release. In the meantime it does sound like we should clarify the terms.

**Comment by nmsmith** [comment]
Oh, I see. Clearly I haven't noticed that subtle distinction.

Consider my confusion evidence that the term "generic" needs to be explicitly defined, then 😉.

**Comment by arthurevans** [comment]
This really requires a total rewrite of the current "Parameterized structs" section to use a non-generic example, and renaming the current section to "Generic structs" or something similar, with appropriate caveats about the current state of generics in Mojo (somewhat rudimentary without a lot of handwritten MLIR). Still useful information because users will be dealing with generic types in the standard library, but we should be clear about the current state of writing generics.
