### ISSUE TITLE
[Feature Request] Modular CLI docs aren't discoverable

### ISSUE THREAD

**Issue by gryznar** [modularml/mojo#1648]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

I request to add official changelog to track changes in `modular` CLI

### What is your motivation for this change?

There is no easy way to track changes, fixes and improvements to this installation tool.

**Comment by arthurevans** [comment]
We actually have a changelog, here: https://docs.modular.com/cli/changelog.html

I think the problem is that it doesn't belong to any of the top-level doc areas (mojo, max engine, max serving), so it doesn't show up in the left-hand navigation. The only way to navigate to it is to click on a link (for example, from the "Get Mojo" page). So we need to figure out how to make this easier to find.

**Comment by gryznar** [comment]
It is so suprising to me, that this changelog exists!
