### ISSUE TITLE
[Feature Request] Rename `DynamicVector` and friends

### ISSUE THREAD

**Issue by soraros** [modularml/mojo#1761]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

Rename `DynamicVector` and friends to something more sensible. Like `DynamicArray`, and `InlinedFixedVector` could simply be `Array`, etc.

### What is your motivation for this change?

I find "dynamic vector" a bit tautological, given the "vector" terminology (likely) comes from C++, which literally means ["dynamic sized array"](https://en.cppreference.com/w/cpp/container/vector). `InlinedFixedVector` is even worse, not really dynamic dynamic array, but I guess double negation elimination is a thing.

**Comment by JoeLoser** [comment]
Thanks for filing the GH issue after the Discord discussion.  I kick-started a discussion last week with the Standard Library team and broader Mojo users internally.  We've decided on a new name for `DynamicVector` and we'll communicate the upcoming renames in the changelog.  Still need to decide on a new name for `InlineFixedVector`.

**Comment by gryznar** [comment]
@JoeLoser could you please take a look at this issue: https://github.com/modularml/mojo/issues/1528? This is also related to renaming and will be the best to take steps with this sooner than later :)

**Comment by nmsmith** [comment]
@JoeLoser As part of the rename, may I suggest also renaming `CollectionElement` to `CollectionItem`? This would improve consistency with the `getitem`, `setitem`, and `delitem` dunder methods which currently manipulate "Elements" despite their name implying that they manipulate "Items".

As a separate issue, the type parameter of `DynamicVector` (and related types) should probably be named `Item` instead of `T`,  since that is more descriptive/self-documenting.

**Comment by soraros** [comment]
Now the `DynamicVector` is gone, what about
- `InlinedFixedVector`
- `StaticTuple`, which is clearly an array, even the IR says so.
- `StaticIntTuple`, do we still need this type?

**Comment by soraros** [comment]
@JoeLoser Can we consider this done?
