### ISSUE TITLE
[Docs] Wrong indentations in blog post examples

### ISSUE THREAD

**Issue by gryznar** [modularml/mojo#1818]
### Where is the problem?

https://www.modular.com/blog/what-are-dunder-methods-a-guide-in-mojo

### What can we do better?

![image](https://github.com/modularml/mojo/assets/90425096/93555516-d3b5-4504-8a2d-23aa82272198)

1) and 2) should work (despite too big indentation, but 3) is invalid IMHO (block defined via loop should be deeper indented)

Additionally:
![image](https://github.com/modularml/mojo/assets/90425096/cba4d580-49d0-427b-9283-2ec61ceb323f)

**Comment by hogepodge** [comment]
Thanks @gryznar, I've made the changes and they should go live in the next site update. It turns out it was a tabs vs. spaces issue. The supporting code is live in the corresponding GitHub repository, and that should be guaranteed to work with the published version of Mojo (although given the time since publication, it likely doesn't work any more and will need updates to match the latest Mojo language def).
