### ISSUE TITLE
[Feature Request] Please rename `Reference` to `Ref`

### ISSUE THREAD

**Issue by ehsanmok** [modularml/mojo#1881]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

It'd be great to use `Ref` instead of the existing `Reference` that also aligns with shorter keywords like `fn`, `struct` etc.

### What is your motivation for this change?

Conciseness

**Comment by JoeLoser** [comment]
I'm +1 for this from library perspective.

**Comment by laszlokindrat** [comment]
Thanks for opening the ticket! The team discussed shortening the names of certain types that might be commonly used in the future (e.g. `Reference`, `Optional`, `Pointer`). We would like to highlight that while shortening commonly used keywords has many precedents in both Mojo and Python (e.g. `def`, `fn`, `var`), shortening type names is not nearly as obvious. We decided that, in order to avoid unnecessary churn, we will be careful with name changes until the semantics of these most common types are settled, and we have explicit naming guidelines.
