### ISSUE TITLE
[BUG]: regression with modular install --install-version

### ISSUE THREAD

**Issue by guidorice** [modularml/mojo#1887]
### Bug description

`--install-version` was added to support version pinning of mojo, ex: in CI/CD environments. [I have been using this successfully in the mojo-pytest project](https://github.com/guidorice/mojo-pytest/blob/44f41447e01a24cc51a0fe9d76ad5b188887cfd6/.github/workflows/test.yml#L16).
With 24.1 this version pinning no longer works. Tried on both MacOS and also the Github Actions runner ([Linux](https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20240225.1))

### Steps to reproduce

```
$ modular install --install-version 24.1.0 mojo
modular: error: no packages found for the current target hardware - please run `modular host-info` and file a ticket at https://github.com/modularml/max with your hardware information

$ modular host-info

 Host Information
  ================

  Target Triple: aarch64-unknown-macosx
  CPU: apple-m1
  CPU Features: aes, complxnum, crc, dotprod, fp-armv8, fp16fml, fullfp16, jsconv, lse, neon, pauth, ras, rcpc, rdm, sha2, sha3

```

### System information

```shell
Darwin macbook.local 23.3.0 Darwin Kernel Version 23.3.0: Wed Dec 20 21:33:31 PST 2023; root:xnu-10002.81.5~7/RELEASE_ARM64_T8112 arm64
mojo 24.1.0 (55ec12d6)
modular 0.5.1 (1b608e3d)
```

**Comment by zbowling** [comment]
You can use `modular install mojo --install-version 24.1.0-55ec12d6-release`. The command doesn't understand how to parse partial version numbers and requires fully qualified versions which have become more verbose as of late. You can get the full version string from more recent mojo packages by reading the VERSION file in the ~/.modular/pkg/packages.modular.com_mojo/ folder. 

Please note that the --install-version flag was more was more field testing and debugging user issues and less a supported feature like for CI/CD environments until Mojo stabilizes and we have a more long term supported version of Mojo. Older versions of Mojo may stop working with newer versions of the modular CLI at any point because the contract between packages and the Modular CLI is still evolving (generally the CLI is backward compatible with a version or two but anything older is guaranteed to work).
