### ISSUE TITLE
[Feature Request] Make `Bool` `Intable`

### ISSUE THREAD

**Issue by soraros** [modularml/mojo#2168]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

As title.

### What is your motivation for this change?

I don't see reason to hold it off any longer.

### Any other details?

N/A

**Comment by bgreni** [comment]
I see there's no way to self assign issues, but I've been looking for an easy first issue so I'd like to take this one!

**Comment by gabrieldemarmiesse** [comment]
Oups @bgreni , I started and didn't see your message. Here is the PR: #2181

**Comment by gabrieldemarmiesse** [comment]
Fixed in #2181 I think you can close the issue @soraros

**Comment by JoeLoser** [comment]
Fixed in https://github.com/modularml/mojo/commit/07115011741d3a3c51d87085c3f54c60d701f270.  I need to dig into why "Fixes <blah>" in commits that land aren't auto-closing issues; likely due to some GitHub permissions since contributors don't currently have write access I think (which is also the problem for why you can't add labels or assign issues).

**Comment by soraros** [comment]
Thanks a lot @gabrieldemarmiesse!
