### ISSUE TITLE
[Feature Request] Add an `offset` method to `AnyPointer`.

### ISSUE THREAD

**Issue by soraros** [modularml/mojo#2171]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

As title.

### What is your motivation for this change?

- `Pointer` has it. In order to unify `Pointer` and `AnyPointer`, we should also add it to `AnyPointer`.
- `__add__` looks too cute, and prevents method chaining.

### Any other details?

Maybe make `__add__` less generic than `Pointer.__add__`, so we can prevent adding two pointers together (both pointer types are `Intable`). More concretely, now, we have:

```mojo
struct AnyPointer:
    fn __add__(self, rhs: Int) -> Self: ...
    fn __sub__(self, rhs: Int) -> Self: ...

struct Pointer:
    fn offset[T: Intable](self, offset: T) -> Self: ...
    fn __add__[T: Intable](self, rhs: T) -> Self: ...
    fn __sub__[T: Intable](self, rhs: T) -> Self: ...
```

I propose we move to:

```mojo
struct AnyPointer:
    fn offset[T: Intable](self, offset: T) -> Self: ... # retain a little bit of convenience 
    fn __add__(self, rhs: Int) -> Self: ...
    fn __sub__(self, rhs: Int) -> Self: ...
```

Or even better:

```mojo
struct AnyPointer:
    fn offset(self, offset: Int) -> Self: ...
    fn __add__(self, rhs: Int) -> Self: ...
    fn __sub__(self, rhs: Int) -> Self: ...
```

**Comment by StandinKP** [comment]
I will take this up. So should I use the generic or directly use offset: int?

**Comment by soraros** [comment]
@StandinKP yea, let's wait for input from the team. That's why I didn't create a PR.

**Comment by JoeLoser** [comment]
I'm actually going to suggest we no longer do this. Internally, today, @lattner pushed on removing `lit.ref.offset` which is what `Pointer` used internally in its offset function. So, in the next nightly release, `Pointer.offset` is removed. So, we should hop on that ship and not introduce a new offset function to `AnyPointer.` The original motivation in here  for parity with `Pointer` to help us with moving uses of `Pointer` over to `AnyPointer`. However, that argument is no longer sound since we soon remove offset from `Pointer` 😄
