### ISSUE TITLE
[BUG] bit_length used in StaticTuple causes crash at compile time

### ISSUE THREAD

**Issue by Benny-Nottonson** [modularml/mojo#2236]
### Bug description

When trying to compute the binary representation of a number at compile time, the below code causes a crash in the compiler, potentially related to #2218 

## Code
```mojo
from math.bit import bit_length

alias Bits = StaticTuple[Bool, _]

fn binary[Number: Int]() -> Bits[bit_length[DType.int64, 1](Number).to_int()]:
    return Bits[bit_length[DType.int64, 1](Number).to_int()]()

fn main():
    var bits = binary[5]()
    print(bits[0])
```
    
## Full output
 ```bash
 /__w/modular/modular/Kernels/mojo/stdlib/builtin/_startup.mojo:132:4: error: no viable expansions found
/__w/modular/modular/Kernels/mojo/stdlib/builtin/_startup.mojo:132:4: note:   call expansion failed - no concrete specializations
/__w/modular/modular/Kernels/mojo/stdlib/builtin/_startup.mojo:63:4: note:     no viable expansions found
/__w/modular/modular/Kernels/mojo/stdlib/builtin/_startup.mojo:78:14: note:       call expansion failed - no concrete specializations
/home/benny/fibonacci/fibonacci.mojo:8:4: note:         no viable expansions found
fn main():
   ^
/home/benny/fibonacci/fibonacci.mojo:9:25: note:           failed to evaluate 'apply'
    var bits = binary[5]()
                        ^
/__w/modular/modular/Kernels/mojo/math/bit.mojo:361:4: note:             failed to interpret function @math::bit::bit_length[stdlib::builtin::dtype::DType,stdlib::builtin::int::Int](stdlib::builtin::simd::SIMD[$0, $1]),type=si64,simd_width=1
/__w/modular/modular/Kernels/mojo/math/bit.mojo:391:36: note:               failed to fold operation pop.call_llvm_intrinsic{fastmathFlags: #pop<fmf none>, intrin: "llvm.ctlz" : !kgen.string}(#pop<simd 5> : !pop.scalar<si64>, #pop<simd false> : !pop.scalar<bool>)
mojo: error: failed to run the pass manager
```

### System information

```shell
WSL2 Ubuntu v22.04
Mojo v24.2.0
Modular v0.6.0
```

**Comment by JoeLoser** [comment]
Yep, same issue. This is why ord on multi byte characters currently crashes in the parameter domain too.

**Comment by Benny-Nottonson** [comment]
> Yep, same issue. This is why ord on multi byte characters currently crashes in the parameter domain too.

Gotcha, do you want me to continue making separate issues for affected functions that I find, or group them all under the original issue?

**Comment by JoeLoser** [comment]
> > Yep, same issue. This is why ord on multi byte characters currently crashes in the parameter domain too.
> 
> Gotcha, do you want me to continue making separate issues for affected functions that I find, or group them all under the original issue?

I think grouping them all under one issue would be easiest.  It's actually quite easy to search in `math.mojo` internally for any use of `llvm_intrinsic` and it would fail in the parameter domain if said code path is taken since we don't evaluate `llvm_intrinsic` when in the parameter domain.  I think this is quite limiting, especially for things that build on top of these math libraries, such as the multi-byte `ord` thing recently in https://github.com/modularml/mojo/commit/9a119f6a6ed44b10e0c74bfd217147f4ae7df844.

I've raised this as a talking point internally in this week's Mojo meeting internally, but it may get pushed to next week since I have to miss this week's meeting.  In any case, I'll take an AI to update this/other GH issues with whatever gets discussed so it's shared with the public.
