### ISSUE TITLE
[BUG] unexpected result when running `len(my_list)` on a list created with a `capacity` argument

### ISSUE THREAD

**Issue by dimitrilw** [modularml/mojo#2450]
### Bug description

```mojo
fn main():
    var cap = 3
    var l = List[Int](capacity=cap)
    print("l:")
    for i in range(cap):
        l[i] = i * i
        print(" ", i, "=", l[i])
    print("l[2] =", l[2])
    print("len(l) =", len(l))
```

Output:
<img width="190" alt="image" src="https://github.com/modularml/mojo/assets/5898931/10b4d772-e114-48d3-a7d6-9d50f07f013f">

I expected the final `print()` to say `len(l) = 3`.

### System information

```shell
- What OS did you do install Mojo on ?
MacOS Sonoma 14.4.1

- Provide version information for Mojo by pasting the output of `mojo -v`
mojo 2024.4.2621 (6dff3016)

- Provide Modular CLI version by pasting the output of `modular -v`
modular 0.7.2 (d0adc668)
```

**Comment by mikowals** [comment]
`capacity` is the number of element spaces allocated in memory.  `size` is the number of elements currently in the List.  `len(l)` reads `size` not `capacity`.  When filling a list after allocating, you probably want to use `append` so that the `size` of the list grows as you add elements.  Alternately you can call `resize` which will adjust the size and insert a specified value from the current `size` to the new `size`. 

The documentation on the fields is [here](https://docs.modular.com/mojo/stdlib/collections/list#list).  This is a really common misunderstanding and hopefully it become more clear when `List` gets bounds checking.

**Comment by dimitrilw** [comment]
It seems a bit counter-intuitive that it was this easy to cause `len()` to return an invalid result.

**Comment by dimitrilw** [comment]
And I *do* hear you re bounds checking. Marking issue closed.
