### ISSUE TITLE
[Feature Request] Rust-like `Result<T, Error>` type

### ISSUE THREAD

**Issue by Omicronlawful** [modularml/mojo#259]
## Request
Result type like rusts

### Motivation
It makes handling errors easier and the code saver.

### Description and Requirements

it could be implemented as an option or a function that checks for an error. A function like is_ok() would call a try catch block and return something like Result<T, Error>. These errors would then need to be handled and would raise awareness for an error and prevent runtime errors. The result Enum should also have a throw method which reverts to the try catch behavior. I would love to see the result as a default instead of the try catch, but I guess it’s unlikely because you are trying to make the new languages as similar as possible to python. The ? Like in rust would be also very important for that.

**Comment by JorgeRuizDev** [comment]
I personally prefer using result types instead of exceptions because they tend to be more efficient, they do not require extra identation and can be explicitly declared in the function/method signature. 

However, I don't think it's a good idea to have both exceptions and result types in a programming language. It can lead to a situation where different libraries use different approaches, so we will end up mixing both methods in our codebase...

There are libraries that add Result to Python and suffer from the exact same problem... 

A solution  would be to have an alternative syntax to catch those exceptions but the function signature should somehow include the possible risen exceptions like in the result type...

**Comment by lattner** [comment]
I agree, this is pretty obvious IMO.  We mentioned Optional in the roadmap but didn't explicitly call out Result.  I just added it, because it will be one of the things added when ADT's and traits are in place.  I'm closing this issue now just to help declutter the issue tracker now that it is part of the roadmap.  Thank you for calling this out!
