### ISSUE TITLE
[BUG] Mojo build crashes when using Optional and struct

### ISSUE THREAD

**Issue by ericqu** [modularml/mojo#2670]
### Bug description

The following code crashes the 'mojo build' on Apple M1.
```
from collections import Optional

@value
struct Tree:
    var left :Optional[Tree]
    var right :Optional[Tree]

fn main() -> None :
    var t = Tree(Optional[Tree](None), Optional[Tree](None))
```

I was experimenting with Optional, so I likely did something wrong, although I hoped for a compiler error, not a crash.
I wonder if it is related to the recursive nature of the `struct`, although it seems a natural way to implement something like a tree.

### Steps to reproduce

the source code is provided in the description above. Then I execute `mojo build src/test_bin.mojo` and it gives:
```
[47079:11093979:20240515,231828.233868:WARNING crash_report_exception_handler.cc:257] UniversalExceptionRaise: (os/kern) failure (5)
zsh: illegal hardware instruction  mojo build src/test_bin.mojo
```
or sometimes: 
```
[47132:11096302:20240515,232253.957242:WARNING crash_report_exception_handler.cc:257] UniversalExceptionRaise: (os/kern) failure (5)
zsh: bus error  mojo build src/test_bin.mojo
```
I did also try on the playground and got the following crash details 
[mojo-stack.txt](https://github.com/modularml/mojo/files/15327236/mojo-stack.txt)

It looks like there are other issues reported with Optional, although they don't crash the compiler. 
Let me know if any other information could help.

### System information

```shell
- What OS did you do install Mojo on ? MacOs with Apple M1
- Provide version information for Mojo by pasting the output of `mojo -v` : mojo 24.3.0 (9882e19d)
- Provide Modular CLI version by pasting the output of `modular -v` : modular 0.8.0 (39a426b5)
```

**Comment by Ryul0rd** [comment]
This is because your struct is recursive. A struct has all its fields stored contiguously in memory and the total size is the sum of the size of those fields. This means you can't have a struct with a field that has the same type as the struct itself because you get infinite recursion trying to determine the size. You get around this by using pointers since a pointer has fixed size regardless of what's being pointed to.

The fact that you get a crash instead of a useful error is still an issue though. The mojo vscode plugin also crashes if you attempt this.

**Comment by Mogball** [comment]
The crash -- it should emit an error

**Comment by YichengDWu** [comment]
It's malfunctioning again.
