### ISSUE TITLE
[BUG]: cannot be converted from 'fn(Person) -> Person' to 'fn(Person) -> Person'

### ISSUE THREAD

**Issue by sa-** [modularml/mojo#271]
### Bug description

I was trying to make a small implementation for a list that supports memory only types and I came across a bug - not sure if this is a known issue or not. The code throws an error that I don't quite understand
```
`method argument #0 cannot be converted from 'fn(Person) -> Person' to 'fn(Person) -> Person'`
```

### Steps to reproduce

```shell
from Vector import DynamicVector
from List import VariadicList
from String import String

@value
struct List[T: AnyType]:
    var data: DynamicVector[Pointer[T]]
    
    fn __init__(inout self, *args: T):
        let args_list: VariadicList[T] = args
        var dv = DynamicVector[Pointer[T]](args_list.__len__())
        for i in range(args_list.__len__()):
            var value = args_list[i]
            let ptr = Pointer[T].address_of(value)
            dv.push_back(ptr)
        self.data = dv

    fn map[T_return: AnyType](self, f: fn(T) -> T_return) -> List[T_return]:
        var new_vec = DynamicVector[Pointer[T_return]](self.data.size)
        for i in range(self.data.size):
            let old_value = self.data[i].load()
            var new_value = f(old_value)
            
            let ptr = Pointer[T_return].address_of(new_value)
            new_vec.push_back(ptr)
            
        return List[T_return](new_vec)
    
    fn __getitem__(self, i: Int) -> T:
        let value = self.data[i].load()
        return value

@value
struct Person:
    var name: String
    var age: Int


let listy_mclistface = List(Person("Bob", 1))

fn birthday(p: Person) -> Person:
    return Person(p.name, p.age+1)

fn is_bob(p: Person) -> Bool:
    return p.name == "Bob"

## Running the code
listy_mclistface
    .map[Person](birthday) # also fails when I don't specify the Person type param
    .filter(is_bob)
```

And this is the error message:
```
error: Expression [1]:62:21: invalid call to 'map': method argument #0 cannot be converted from 'fn(Person) -> Person' to 'fn(Person) -> Person'
        .map[Person](birthday) # also fails when I don't specify the Person type param
~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~

Expression [1]:21:5: function declared here
    fn map[T_return: AnyType](self, f: fn(T) -> T_return) -> List[T_return]:
    ^
```
```


### System information

_No response_

**Comment by lattner** [comment]
This gets back to a problem with our generics system, where AnyType doesn't bind properly to memory-only types - memory only types need to be passed indirectly, but AnyType assumes register passability.  The two types that are incompatible are the actual type of the callee (which is correct given Person is a memory-only type:

`!kgen.signature<(!pop.pointer<@"$test"::@Person> byref_result, !pop.pointer<@"$test"::@Person> borrow_in_mem) -> !lit.none>`

and the expected substituted type: 
`!kgen.signature<(!kgen.declref<@"$test"::@Person> borrow) -> !kgen.declref<@"$test"::@Person>>`

which is incorrect, because the substitution doesn't change the result type to being returned by reference.

Generally, one could work around this problem by marking Person as a register_passable type, but it contains a string which is not itself register passable.  It looks like we are getting forced to fix this long standing issue type pararameter binding.

@Mogball and @tatianashp  could you add this to the list of things to talk about next week?

**Comment by lattner** [comment]
There is a similar problem with AnyType of non-trivial register_passable types, anytype is being treated as being trivial (because we don't have traits, so can't reason about copy ctor/dtor etc) which prevents it from substituting in, producing other confusing error messages. When person is @register_passable, we get the same error as before due to a mismatch between the actual and substituted types of:
```
 !kgen.signature<(!kgen.declref<@"$test"::@Person> borrow) ownedresult -> !kgen.declref<@"$test"::@Person>>
 !kgen.signature<(!kgen.declref<@"$test"::@Person> borrow) -> !kgen.declref<@"$test"::@Person>>
```

**Comment by sa-** [comment]
Thanks for the detailed answer! 

I'm trying to implement backpropagation for neural nets using my `Tensor` implementation where I need to keep track of a computation graph, for which I could really use a `List` type. I can probably think of a workaround in the meanwhile until this is fixed though

**Comment by lattner** [comment]
This is going to be tricky to address in the immediate term.  In the absence of traits/protocols (which is scheduled to start in ~2-3 months) we can't reason about what members a generic AnyType has, nor can we constrain type type.  This is actually a pretty big deal, because we don't have the infra to map back to what a substituted type's destructors are.  As a consequence of this, it is only possible to use trivial types like Int/FP with generic algorithms.  This is incredibly constraining right now :-(

There is a separate issue where register_passable and memory-only types have different concrete ABIs / conventions.  This is solvable in a simple way (just treat register passable types as memory abi when generic) or a fancier way (delay binding of ABI until type substitution)... but until we solve the trait issue, we'll still only be able to express generic algorithms over trivial types, even if they are memory only.  So solving this in the immediate term isn't much of a relief.

The best workarounds right now are pretty ugly:
1) Limit your generic code to trivial register passable types; e.g. add an explicit delete() method that you manually manage instead of a `__del__` method that is automatically invoked.
2) Copy and paste things to make them non-generic.

sorry, this is pretty annoying to me too.  I really want to get on top of this of course.

**Comment by sa-** [comment]
No worries and no rush at all! The fact that it's a priority is reassuring enough. At least personally I have no problem waiting for the right implementation that takes as long as it needs. 

Thank you for the suggestions, I will experiment with what works best

**Comment by yakupc55** [comment]
You can use the map method with the data transfer layer:
an example for you:
[https://github.com/yakupc55/mojo-example/blob/main/Map%20method.md](https://github.com/yakupc55/mojo-example/blob/main/Map%20method.md)

**Comment by Mogball** [comment]
As Chris mentioned, the underlying signature of `birthday` is actually `fn(Person&, Person) -> None` whereas the function substitutes `T` and expects `fn(Person) -> Person`, but the diagnostic printer will print the former as the latter. I'll fix the error message, but otherwise this is something that will have to be resolved later^TM.
