### ISSUE TITLE
[Docs] List/Dict Comprehension Section Outdated

### ISSUE THREAD

**Issue by cameronangliss** [modularml/mojo#2750]
### Where is the problem?

https://github.com/modularml/mojo/blob/main/docs/roadmap.md

### What can we do better?

It is no longer true that "Mojo's standard library has not yet grown a standard list or dictionary type", so the docs need updating.

### Anything else?

I'm really looking forward to seeing List/Dict comprehensions get added to Mojo! Thanks!

**Comment by Brian-M-J** [comment]
This has already been fixed in the nightly branch: see [commit 6890241](https://github.com/modularml/mojo/commit/68902417140ebe0592244dde17abd174eb1d6422#diff-6a17656d764b8e1930354f341cf7f47960b63845c3046edcd8bbf282aaa2f464L310).

Whenever the docs site syncs with the nightly branch (might be on the next Mojo release), this issue will automatically be fixed.

**Comment by cameronangliss** [comment]
Ok, thanks! Closing now.
