### ISSUE TITLE
[stdlib] [BUG] `InlineArray` does not invoke the destructors of its elements

### ISSUE THREAD

**Issue by JoeLoser** [modularml/mojo#2869]
`InlineArray` contains values of `AnyType` and copies on construction but does not invoke the destructors of its elements.  We need to fix this.

**Comment by GeauxEric** [comment]
Was attempting on this issue, but I found the `ElementType` is actually `CollectionElement`, not `AnyType` in the latest nightly branch: https://github.com/modularml/mojo/blob/nightly/stdlib/src/utils/static_tuple.mojo#L250

Am I missing something here?

**Comment by rd4com** [comment]
@JoeLoser  it seem like an important one:
`InlineList` uses it and possibly more types,
it might also be blocking `SBO` by @gabrieldemarmiesse.
I'll put this issue on the chat to see if somebody can work on it!

**Comment by rd4com** [comment]
#### Challenge: *values need to be initialized, before calling destructor on the elements*

This `__init__` makes it possible to create an array with uninitialized elements:
 ```mojo
   fn __init__(inout self, *, unsafe_uninitialized: Bool):
  ```

maybe `unsafe_uninitialized` need to be a parameter of `InlineArray`, with a default value of `False` ?

We could then do `@parameter if not unsafe_uninitialized: destroy_pointee all elements`

&nbsp;

How to be sure of which elements are initialized, if an user create a `unsafe_uninitialized` instance,

and initialize only some elements with `UnsafePointer` and `initialize_pointee_*`:

- should user free them all manually with a `DestroyElement` method ?

&nbsp;


Possible incomplete implementation:
```mojo
fn __del__(owned self):
    @parameter
    if not unsafe_uninitialized:
        @parameter
        for i in range(size):
            destroy_pointee(self.unsafe_ptr().offset(i))

```

**Comment by gabrieldemarmiesse** [comment]
Some more information:
* `InlineList` is not affected by this bug because when I coded it I assumed that the InlineArray wasn't running destructors, thus I did It myself: https://github.com/modularml/mojo/blob/nightly/stdlib/src/collections/inline_list.mojo#L155 
* `InlineList` wants to manage itself the destructor of its elements because it does not want to run the destructor of all elements when the array is not completely filled. So just adding a `destroy_pointee` in the `__del__` is not a good solution, we should do better.
* `Inlinelist` sees `InlineArray` like a pointer. It's a piece of memory that is not aware of things like destructors.
* The implementation of small buffer optimization I made is not affected by this bug too because, as `InlineList`, I considered `InlineArray` as a piece of memory, like a pointer, that doesn't manage the elements destructors. Since it has the same properties of a pointer, it makes the SBO very efficient as we can use a pointer that points to either an `alloc()` piece of memory, or points to an `InlineArray` and we just run the destructors in the List. Thus there is no `if` branch in most operations, making this very efficient.

Long story short, the `InlineArray` is currently unsafe, like an `UnsafePointer` and is very useful as-is. If we want a **safe** inline array, then it should be another struct, like `SafeInlineArray` (name to be defined) , that may possibly call to `InlineArray` inside to allocate memory.

Quick overall plan I have in mind, please give feedback:
1) We rename `InlineArray` to `UnsafeInlineArray`
2) We make `InlineList` use `UnsafeInlineArray` under the hood (just some renaming)
3) We make SBO use `UnsafeInlineArray` under the hood (just some renaming)
4) We create a new struct `InlineArray` which uses `UnsafeInlineArray` under the hood, but will always assume that the array is completely filled, will not provide `unsafe_uninitialized`, and will call the destructors of **all** elements in the `__del__`. This can be used by end users as a fixed-sized list responsible for all its elements. This stuct will not provide methods like `pop` or `remove`, but will provide `__setitem__` which will run the destructor before inserting the new element.

**Comment by bgreni** [comment]
I agree with @gabrieldemarmiesse. This behaviour isn't necessarily bad, but it should be renamed and users need to be made aware that they have the burden of destroying it's contents if they want to use it.

**Comment by ConnorGray** [comment]
Thanks for your analysis Gabriel. IMO the problem here is not with `InlineArray`'s semantics, its misuse of the `unsafe_uninitialized` constructor (and arguably that constructor is _way too easy_ to misuse).

Short term, we should _clearly_ document that one of the safety conditions of the `unsafe_uninitialized` constructor is that either:

* All elements must be initialized before the `InlineArray` value is destroyed
* The caller must explicitly use the not-yet-existing-in-Mojo equivalent of [`std::mem::forget(array)`](https://doc.rust-lang.org/stable/std/mem/fn.forget.html). (I've actually added this in a branch but the semantics are somewhat tricky.)

Longer term, I think its probable that Mojo's current representations for uninitialized memory (e.g. see uses of `kgen.undef` / `kgen.unknown`) are likely to run into the same design problems that forced Rust to deprecate [`std::mem::uninitialized()`](https://doc.rust-lang.org/stable/std/mem/fn.uninitialized.html). And if we walk that same path, we'll likely arrive at a design similar to its [`MaybeUninit<T>`](https://doc.rust-lang.org/stable/std/mem/union.MaybeUninit.html) type.

If we had `MaybeUninit` in Mojo, we could:

* Make `InlineArray` run destructors, always.
* Replace `InlineArray.__init__(unsafe_uninitialized)` with `InlineArray.uninitialized[T, size]() -> InlineArray[MaybeUninit[T], size]`

An `InlineArray[MaybeUninit[T]]` would be safe because the `MaybeUninit` type by definition does not assume its contents are initialized, so its destructor is a noop.

**Comment by gabrieldemarmiesse** [comment]
Thanks for the pointers (haha pun intended) @ConnorGray . `InlineList` currently does not use any of the three strategies mentionned here. Does that mean that `InlineList` has a bug somewhere? If not, does that means that `InlineList` uses unitinialized memory correctly and thus makes this a 4th way of using uninitialized memory correctly?

**Comment by ConnorGray** [comment]
> Does that mean that `InlineList` has a bug somewhere?

I think technically yes, its just perhaps not currently easy to run into because `InlineArray` does not have its own destructor. I think this constructor for `InlineList` is arguably a bug, or at the very least very unsafe but not documented as such:

```
    @always_inline
    fn __init__(inout self):
        """This constructor creates an empty InlineList."""
        self._array = InlineArray[ElementType, capacity](
            unsafe_uninitialized=True
        )
        self._size = 0
```

The issue is masked by the fact that:

* `InlineList` itself _correctly_ only destroys elements up to its `_size`. 
* `InlineArray` _incorrectly_ does not run destructors on all its elements (which IMO as mentioned above is a bug we should fix).

So perhaps its not a bug per se today, but the intersection of these issues I think it's quite the optimal design for each type individually.

**Comment by gabrieldemarmiesse** [comment]
I see. Thank you for the explanation. I always assumed that `InlineArray` was just "a bunch of bytes allocated on the stack to manipulate however we want, similar to `UnsafePointer.alloc()`". This is right now the case. Would this still be the case with `InlineArray[MaybeUninit[T]]`? If not, what could we use to serve as storage of `InlineList`?

**Comment by ConnorGray** [comment]
I think `InlineArray` ought to be a higher-level type, more analogous to [`std::array`](https://en.cppreference.com/w/cpp/container/array) in C++ or [`[T; N]`](https://doc.rust-lang.org/std/primitive.array.html) in Rust.

An `InlineArray` should always (barring short regions of unsafe code) be fully initialized, and it should run destructors on its values.

> Would this still be the case with InlineArray[MaybeUninit[T]]?

I think so, `InlineArray[MaybeUninit[T]]` could be a reasonable way for us to express a not-yet-fully-initialized array in Mojo.

> If not, what could we use as storage of InlineList?

I think your suggestion of adding a lower-level `UnsafeInlineArray` could be one approach. I also think changing `InlineList._array` to actually be an `InlineArray[MaybeUninit[ElementType]]` would also be a good solution.

To illustrate what that might look like, and for simplicity assuming our Mojo `MaybeUninit` equivalent type mirrors the API of its Rust inspiration, here's what `InlineList.__del__` might look like:

```mojo
struct InlineList[..](..):
    var _array: InlineArray[MaybeUninit[ElementType]]

    # ...

    fn __del__(owned self):
        for i in range(self._size):
            self._array[i].unsafe_assume_init_destroy()
```

Where `unsafe_assume_init_destroy()` is our variant of [`MaybeUninit::assume_init_drop()`](https://doc.rust-lang.org/stable/std/mem/union.MaybeUninit.html#method.assume_init_drop).

Similarly, here's what `InlineList.__getitem__` could look like:

```mojo
    fn __getitem__(self: Reference[Self, _, _], owned idx: Int
    ) -> ref [self.lifetime] Self.ElementType:
        # ...
        return self[]._array[idx].unsafe_assume_init_ref[self.lifetime]()
```

Where `unsafe_assume_init_ref()` similarly would be our variant of [`MaybeUninit::assume_init_(ref|mut)`](https://doc.rust-lang.org/stable/std/mem/union.MaybeUninit.html#method.assume_init_ref).

Apologies for all the Rust analogies 🦀 —Rust just happens to have walked a similar set of design constraints. Just like Mojo is avoiding having to design the Pythonic parts of the language from scratch by taking inspiration from Python, similarly for these low level API design situations involving uninitialized memory, safe API wrappers, and lifetimes, we can stand on the shoulders of folks who've already made and learned from mistakes in this area 🙂

**Comment by gabrieldemarmiesse** [comment]
@ConnorGray I tried my best to implement a `MaybeInit` in #2888 , let me know if that makes sense or not.

**Comment by gabrieldemarmiesse** [comment]
We have the final fix here: https://github.com/modularml/mojo/pull/2965 🙂
