### ISSUE TITLE
[BUG] `List` doesn't work at compile time.

### ISSUE THREAD

**Issue by soraros** [modularml/mojo#3126]
### Bug description

As title. At least `List.__getitem__` doesn't work.

### Steps to reproduce

```mojo
fn main():
    alias l = List[Int](1, 2, 3)
    print(l[0])  # prints 0
```

### System information

```shell
Mojo 2024.6.2614 (366c690a) on Docker, Intel Mac
```

**Comment by DWSimmons** [comment]
I went back in time (modular clean; modular install nightly/mojo --install-version) and found that this bug does not exist in 2024.6.2305 but does exist in 2024.6.2505.

Additionally, there is some odd - to me as I am truly a rookie with extra time on his hands - behavior.  If some additional light could be shed on the following, I would greatly appreciate it.

As expected: 
In 2024.6.2305 through to today (Note use of `var`)
```
fn main():
    var l = List[Int](1, 2, 3)
    print(l[0])  # prints 0
```
In 2024.6.2305 `alias` behaves as expected
```
fn main():
    alias l = List[Int](1, 2, 3)
    print(l[0])  # prints 1
```
However, in 2024.6.2505
```
fn main():
    alias l = List[Int](1, 2, 3)
    print(l[0])  # prints 0
```

**Comment by DWSimmons** [comment]
Possibly related to  https://github.com/modularml/mojo/pull/2847 ?

**Comment by mikowals** [comment]
There is [some history](https://github.com/modularml/mojo/pull/2294#issuecomment-2065916684) of compile time issues as collections switched to returning references.  But there is at least one [use of alias List  in the stdlib](https://github.com/modularml/mojo/blob/main/stdlib/src/builtin/dtype.mojo#L748-L771) so that problem seems to have been solved or occurs much more narrowly than in [previous implementations](https://github.com/modularml/mojo/issues/2543).

If this is a recent breakage as mentioned above then it is probably [this commit](https://github.com/modularml/mojo/commit/620b26091e3eb4a47b1d6a7a3cad7ba0e959d95f).   My PR (#2847 ) was merged afterward just for the changes to tests if I understood the comment there correctly.

**Comment by gabrieldemarmiesse** [comment]
I think we need way more "compile time tests" because those regressions/bugs are really frequent. Not many structs are currently tested at both compile-time and runtime. This could be a very good "good first issue".

**Comment by ematejska** [comment]
Is this a dup of [https://github.com/modularml/mojo/issues/3098](https://github.com/modularml/mojo/issues/3098)?

**Comment by soraros** [comment]
> Is this a dup of #3098?

@ematejska I don't think so. #3098 likely has something to do with `Tensor` and not `List`.

**Comment by ematejska** [comment]
@DWSimmons Thanks for the detailed analysis here. Looks like a regression.

**Comment by ematejska** [comment]
This is getting worked on, thanks for reporting.

**Comment by lattner** [comment]
`ref` arguments can now bind to the temporaries that parameter expressions are emitted into, fixing this.  Thank you for the report!

**Comment by helehex** [comment]
I think there may still be some issues in this area when things get more complicated.
