### ISSUE TITLE
[Feature Request] Foreign Language Agnostic CFFI Bridge

### ISSUE THREAD

**Issue by XLabOffensive** [modularml/mojo#317]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

```shell
Extend CPython bridge to support arbitrary cffi bindable language
```

### What is your motivation for this change?

```shell
interoperability with arbitrary language is a must have for mobile/cloud/embedded vendor locked in platform development
cffi interface is supported (or easy to add to) majority of the exiting languages
```

### Any other details?

```shell
example implementation of CPython-Go cffi bridge:


https://github.com/nils-werner/python-go-cffi
```

**Comment by abduld** [comment]
The standard library provides [external_call](https://docs.modular.com/mojo/MojoStdlib/Intrinsics.html#external_call) that allows you to call C++ functions. E.g. 
 

```
external_call["cosf", Float32](arg)
```

will call the C cosf funciton

**Comment by strangemonad** [comment]
since I was looking for something similar and this seems like a top google result

1. mojo -> C/C++: as @abduld pointed out there's the `let cos = extern_call[cosf, ...]`
2. C -> mojo by annotating a mojo function with `@extern` and compiling the mojo module to a shared object.

There's example code for all of these in this repo https://github.com/ihnorton/mojo-ffi/tree/ffi-demo by @ihnorton
