### ISSUE TITLE
[BUG] Mojo should block mutating `__getitem__ -> ref ...` call on `alias`

### ISSUE THREAD

**Issue by soraros** [modularml/mojo#3281]
### Bug description

As title.

### Steps to reproduce

```mojo
@value
struct S:
    var data: Int

    @always_inline
    fn __getitem__(ref [_]self) -> ref [__lifetime_of(self)] Int:
        return self.data

fn main():
    alias foo = S(0)
    foo[] = 10
    print(foo[])  # prints 0
```

### System information

```shell
Mojo 2024.7.2205 (9b0e6242)
```

**Comment by lattner** [comment]
I don't think this is a desirable fix for this problem.  Python allows all sorts of weird getitem/setitem things, and Mojo doesn't want to impose "taste" (or even "common sense" :-) ) on library authors.

The issue here is that referring to the alias value "materializes" it into a local, so the code is like:

```
fn main():
    alias foo = S(0)
    var tmp1 = foo
    tmp1[] = 10
    var tmp2 = foo
    print(tmp2[])  # prints 0
```

The behavior is a bit surprising but stacks out from how other parts of the language works.

**Comment by soraros** [comment]
@lattner But the following code doesn't compile:

```mojo
@value
struct S:
    var data: Int

    fn __setitem__(inout self, value: Int):
        self.data = value

fn main():
    alias foo = S(0)  # error: invalid call to '__setitem__': invalid use of mutating method on rvalue of type 'S'
    foo[] = 10
    print(foo[])  # prints 0
```
