### ISSUE TITLE
[BUG] `parallelize` should abort if num_workers < 0, currently it has weird behavior

### ISSUE THREAD

**Issue by SynodicMonth** [modularml/mojo#3312]
### Bug description

```python
from algorithm import parallelize

def main():
    @parameter
    fn parallel(i: Int):
        print(i, end='')
    
    parallelize[parallel](10, 0)
```

when num_workers=0, the parallel fn does not execute.

### Steps to reproduce

Also,
```python
from algorithm import parallelize

def main():
    @parameter
    fn parallel(i: Int):
        print(i, end='')
    
    parallelize[parallel](10, -1)
```
num_workers<0 causes wierd output

when num_workers=-1:
```
12043
```

when num_workers=-2:
```
3012
```

### System information

```shell
- Ubuntu 22.04.4 LTS
- mojo 24.4.0 (2cb57382)
- modular 0.8.0 (39a426b5)
```

**Comment by martinvuyk** [comment]
Hi, thanks for catching this. 

> when num_workers=0, the parallel fn does not execute.

That makes absolute sense to me, you're telling it to execute a function with 0 threads and it does exactly that. It's the same as doing:
```mojo
for i in range(0):
    print("hi")
```
it will do nothing :man_shrugging: 

> num_workers<0 causes wierd output

This can probably be a quick fix by doing `max(0, num_workers)` (or aborting if num_workers < 0). Could you change the title of the issue to refer to that so that this can be fixed by the Mojo team ? (parallelize is not open sourced yet so I can't make a PR)
(reproducible with `mojo 2024.7.2605`)

**Comment by SynodicMonth** [comment]
Yeah that make sense.

Actually this is associated to another bug #3311, where a global variable initialized from num_performance_cores() become 0 after compile. Then the whole parallel body just don't execute. 

Since num_work_items is not zero, if num_workers=0, the program would better complain it can't excecute instead of just don't execute. 
Or we should clarify this in the doc and let the user to add some check.

I've changed the title

**Comment by ematejska** [comment]
This should be fixed in the upcoming nightly.
