### ISSUE TITLE
Generalize `init` argument convention with named result slots

### ISSUE THREAD

**Issue by Mogball** [modularml/mojo#3390]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

Recently, Mojo added named result slots in the form of

```mojo
fn foo() -> String as output:
    String.__init__(output, "hello!")
```

This allows assigning directly into the result of a function. Mojo also secretly has an `init` convention that only applies to the `self` argument of constructors,

```mojo
struct Foo:
    fn __init__(inout self): # 'inout' is a lie! This is actually a different convention
        pass
```

The `inout` argument convention specifies that the argument value is initialized upon entry and *must* be initialized on exit. This sneaky constructor `inout self` is actually uninitialized on entry and must be initialized on exit! This is similar but not exactly the same as `out` arguments in other languages. Because Mojo is hiding things from the user, it's impossible to spell the type of a constructor: 

```mojo
var ctor: fn(inout self: Foo) -> None = Foo.__init__ # error!
```

Because Mojo is lying!

To regularize this, we should create a new `init` argument convention to expose this directly, thus

```mojo
struct Foo:
    fn __init__(init self):
        pass

var ctor: fn(init self: Foo) -> None = Foo.__init__ 
```

At the same time, we can change the syntax of named result slots to this as well,

```mojo
fn foo() -> init out: String:
    String.__init__(out, "hello!")
```

The only nuance here is that `init != out`. Because you can fieldwise initialize an `init` value, but not an `out` value.

```mojo
struct Foo:
    var x: Int

fn foo():
    var value: Foo
    value.x = 1234
    use(value) # 'value' is not initialized. Must call a constructor!

fn bar(init value: Foo):
    value.x = 1234 # ok, 'whole-object' bit is already initialized on entry
```

This is an acceptable tradeoff to generalize the `init` syntax from constructors to any argument and with named result slots.

### What is your motivation for this change?

We should do this!

**Comment by soraros** [comment]
Finally, we can stop lying in constructor signatures!

Does this mean that we can also field initialise the named result slot?

**Comment by martinvuyk** [comment]
> Does this mean that we can also field initialise the named result slot?

nope: 
> The only nuance here is that init != out. Because you can fieldwise initialize an init value, but not an out value.

this would work (as far as I've understood):
```mojo
fn f(init out: S) -> S:
  out.data = ... 
  return out
```

---

Is there no way to somehow say that the output var is the on function entry initialized variable ? That way these two things would become synonyms essentially. 
```mojo
fn f(new out_var: S) -> owned out_var: # initialized on exit
  var out_var = S.__init__()
  return out_var

fn f(init out_var: S) -> owned out_var: # initialized on entry
  out_var.data = ... 
  return out_var
```
and this would become the syntax sugar
```mojo
fn f() -> out_var: S: # initialized on exit
  var out_var = S.__init__()
  return out_var

fn f() -> init out_var: S: # initialized on entry
  out_var.data = ... 
  return out_var
```

I don't know if this makes any sense language wise, `owned` might not be the right concept (`bind` ?). But being able to bind the output to input might also help simplify lifetime annotations (?)

**Comment by nmsmith** [comment]
@martinvuyk 

All of your examples include a `return` statement. With the proposed `init` convention, the idea would be that `return` is just _sugar_ for initializing the result. So the following:
```
fn foo() -> Int:
    return 4
```

Would desugar to:
```
fn foo() -> (init output: Int):
    output = 4
```

Given this desugaring, I think your examples are a bit off-track.

**Comment by martinvuyk** [comment]
Oh yeah you're right, edited now to remove them. But the ideas still hold no?

**Comment by nmsmith** [comment]
I don't think so. For the following example:
```
fn foo() -> (init output: Int):
    output = 4
```

The idea is that `output` _is_ an argument. The only special thing about this argument is that it's listed on the right-hand side of `->`. There's no need for this syntax to desugar to anything else. Calling `foo` looks like this:
```
x = foo()
```

You should view `x` as an **input** to `foo`. It makes more sense if you replace `=` with `<-`:
```
x <- foo()
```

This is just the function signature for `foo` flipped back-to-front. `foo` accepts one argument: `x`.

**Comment by nmsmith** [comment]
@Mogball  I'll share some of my thoughts on the design of this feature.

> The only nuance here is that init != out. Because you can fieldwise initialize an init value

There's a downside to having `init` imply fieldwise initialization: this isn't something that callers need to care about. The conventions that appear in function signatures should ideally only communicate as much information as it relevant to the caller. So the "correct" public convention is really `out`. (Or whatever we want to call that.)

That said, I can see the counter-argument: it would be really nice if `__init__` wasn't actually a special function, and instead its behaviour can be entirely explained by its signature.

That might be a good enough reason to have `init` behave as you propose.

Regarding the keyword: somebody on Discord proposed `new`, and I think that makes a bit more sense, because:
- `new` has a lot of precedent as a keyword in other languages.
- "new" is an actual English word, so it makes for a cleaner keyword.
- This will help prevent programmers from conflating the `new` convention with the `__init__` method itself. (We don't want people to think these two features are tied to each other.)
- This will help us avoid complaints about the redundancy of having to write `init` _twice_ when defining a constructor.

We probably want a reverse convention as well, e.g. `fin`. That's what `__del__` and `__moveinit__` would use.

**Comment by nmsmith** [comment]
The keywords `construct` and `destruct` would lead to a very simple definition for "constructors" and "destructors" in Mojo:
- A constructor is any function that uses the `construct` convention.
- A destructor is any function that uses the `destruct` convention.

Some specific examples:
- `fn __init__(construct self)` is a constructor
- `fn __del__(destruct self)` is a destructor
- `fn __moveinit__(construct self, destruct existing)` is _both_ a constructor and a destructor

A minor quirk: if `-> T` desugars to `-> construct result: T` then technically _every_ function that returns a value would be a constructor, but that's just a technicality I suppose. 🤷‍♂️

**Comment by martinvuyk** [comment]
> I don't think so.
> ...
> The idea is that output is an argument. The only special thing about this argument is that it's listed on the right-hand side of `->`.

Correct me if I'm wrong (I'm an absolute layman in compiler stuff) but afaik Python also includes the concept of `new` for classes where the object is created on exit/inside the func. If we introduce an `init`/`construct` keyword then to me it is very similar to say we'd need to introduce a `new`/`create` keyword where these would be the 2 versions:
```mojo
fn f1() -> out_var: S: # initialized on exit
  out_var = S.__init__()

fn f2() -> new out_var: S: # initialized on exit
  out_var = S.__init__()

fn f3() -> init out_var: S: # initialized on entry
  out_var.data = ... 
```
where `f1()` and `f2()` are considered as having the same signature

> Some specific examples:
> 
> fn __init__(construct self) is a constructor
> fn __del__(destruct self) is a destructor
> fn __moveinit__(construct self, destruct existing: Self) is both a constructor and a destructor

As for these, I personally like having a pair of keywords like `create` & `consume` and letting `construct` hang in the void alone since it is a bit special. So there are 3 easy to explain concepts: create & consume, mutate & borrow & copy, and construct.

**Comment by nmsmith** [comment]
I think you're getting a few things mixed up.

Firstly, while Python classes have both `__new__` and `__init__`, these methods aren't "argument conventions", they're just ordinary methods that are responsible for executing various steps in the object-creation process. Therefore, just because Python has two such methods, doesn't mean Mojo needs two corresponding argument conventions.

More broadly, irrespective of the above methods, Mojo structs are very different to Python classes, so not many concepts that are relevant to classes carry over to structs. There is no evidence that Mojo structs need anything that resembles `__new__`.

>  I personally like having a pair of keywords like `create` & `consume` and letting `construct` hang in the void since it is a bit special

The `destruct` convention that I'm describing is also a "bit special": it's the exact reverse of `construct`. `construct` begins a value's life, and requires its fields to be initialized. `destruct` ends a value's life, and requires its fields to be deinitialized.

**Comment by lattner** [comment]
FWIW, my current opinion on naming is to move these things to nouns, today we have:

```
struct S:
   fn __init__(inout self):
   fn a(self):
   fn b(borrowed self):  # same as 'a'
   fn c(inout self):
   fn d(ref [_] self):
   fn e(owned self):
fn f() -> Int as output:
```

I think we should move to:

```
struct S:
   fn __init__(out self):  # output
   fn a(self):
   fn b(ref self):  # same as 'a', immutable reference
   fn c(mutref self):
   fn d(ref [_] self):
   fn e(owned self):
fn f(out output: Int):
#fn f() -> (out output: Int):
```

**Comment by nmsmith** [comment]
Before we bother repainting the keywords for "references", I would like to publish my bombshell proposal to completely replace lifetimes with something else. 😇

**Comment by lattner** [comment]
Please move quickly!

**Comment by lattner** [comment]
Just for reference, the plan is to change `fn f() -> String as output:` to simply `fn f(out output: String):` aligning it with init methods.

**Comment by nmsmith** [comment]
@lattner How is your proposed syntax supposed to relate to the syntax for _calling_ `f`? As another example, if I have a function `fn g(out x: T, y: T)`, do I call it as `x = g(y)`, or `g(x, y)`?

I would have expected us to keep the `out` convention orthogonal to which side of `=` you put the variable on. For `fn f(out x: T)` you call it as `f(x)`, and for `fn f() -> (out x: T)` you call it as `x = f()`.

With the syntax you're proposing, I'm not sure how all of this fits together.

**Comment by lattner** [comment]
You'd call it like \``x = g(y)``.  This is already true for initializers, where you can have:<br><br>`fn __init__(out self, a: Int)` and then call it with either `result = T(42)` or with `result = T.__init__(42)`.<br><br>The only extension here is to allow it for non-initializers, and not require it to be the first argument.

**Comment by nmsmith** [comment]
Just a note: in Python, and in today's Mojo, `Foo.__init__` is invoked as `Foo.__init__(my_foo)`. It *isn't* invoked as `my_foo = Foo.__init__()`. I don't personally care whether we diverge from Python here (because constructors are already radically different in Mojo), but we should make sure this divergence is a deliberate decision.

Also, `Foo()` desugars to `Foo.__call__()` in Python (which eventually calls `__init__`), so if we want `Foo()` to desugar *directly* to `Foo.__init__()`, we might have to handle this conflict using Mojo's overload resolution rules. This is assuming that Mojo struct objects and/or Mojo class objects are `call`able, as in Python. (Maybe we can diverge from Python here, idk.)

One of the strange consequences of this design for `out` arguments is that not all instance methods would be invokable using `self.f` syntax. Whenever `self` is `out`, the instance method would only be callable using `self = MyType.f()` syntax. For this reason, maybe `out self` should be only allowed for `__init__`. The alternative would be needing to teach everyone that "not all instance methods can be invoked using `self.` syntax". Personally, I think that would be a pointless complexification of Mojo. (Unless there's a simpler mental model that I'm missing.)

**Comment by lattner** [comment]
I landed support for this last night, thank you!

**Comment by lattner** [comment]
> Just a note: in Python, and in today's Mojo, Foo.__init__ is invoked as Foo.__init__(my_foo). It isn't invoked as my_foo = Foo.__init__()

FWIW, the former `Foo.__init__(my_foo)` might still work in the latest nightly, but will be going away.  Here's some intuition:

Consider a memory type like String or YourLargeValue.  If you have a function like `fn getThing() -> YourLargeValue:` the compiler actually compiles this transparently (and has ever since we added support for memory-only types) as `fn getThing(out __result__: YourLargeValue)` (woo, we now have clear syntax for this!).  This is because the address for the result is exposed from the caller to the callee so it can fill in the value.  That said, we don't allow you to /call/ getThing using `getThing(someUninitValue)`. 

The compiler has been in a transient state (and still is a bit internally) but it is much more consistent to make all this stuff line up and be the same.
