### ISSUE TITLE
[Modular CLI] Issue when installing max

### ISSUE THREAD

**Issue by pirsonxyz** [modularml/mojo#3407]
### Issue description

When trying to install max with ```modular install max``` i get this error: ```modular: error: http error: failed to reach URL https://packages.modular.com/max/1.root.json with cURL error SSL connect error```. I have tried installing a different version and using ```modular install mojo``` but it does not seem to solve the issue. (venv with Python version: 3.12.4).

### Steps to reproduce

- Install modular
-  Try installing max with ```modular install max```

### Version Info

```shell
- Provide Modular CLI version by pasting the output of `modular -v` modular 0.9.2 (b3079bd5)
- What OS did you install modular CLI on ? Arch Linux
```

**Comment by Sharktheone** [comment]
I think that looks a lot like https://github.com/modularml/mojo/issues/670#issuecomment-1712492231 Afaik one solution is to use a VPN to install max.

Since, you're on arch, you'll probably run into some problems, I've made a script, which tries to resolve (some) of these issues: https://github.com/Sharktheone/arch-mojo

If you have installed modular through the AUR, you should be good to go, as it uses that script.
