### ISSUE TITLE
[Docs] Suggest adding Install Mojo in https://docs.modular.com/magic/

### ISSUE THREAD

**Issue by yichi170** [modularml/mojo#3527]
### Where is the problem?

https://docs.modular.com/magic/

### What can we do better?

Not sure whether it is necessary or not, but it may be better to guide users to download Mojo at https://docs.modular.com/magic/ before creating a Mojo project. If following the Magic docs before Mojo docs, may miss installing Mojo before creating a Mojo project with Magic CLI.

<img width="835" alt="image" src="https://github.com/user-attachments/assets/ff285149-e2d8-4013-9be4-a4b36f0b7d65">

**Comment by scottamain** [comment]
Thanks for this feedback @yichi170. I can see how this might be confusing, but you actually cannot install Mojo without a Magic or other conda project. As it says in step one, "By default, mojoproject.toml includes max as a dependency because max is the package that installs Mojo." That means Mojo is installed automatically (with the `max` conda package), which is what makes it possible for you to run `mojo --version` in the second step.

Does that help clear things up, or am I misunderstanding your request?

**Comment by yichi170** [comment]
Thanks for your response! I think you're right. I already forgot what situ I faced, but I tried to reproduce it, and there is nothing happened. I will close this issue. Thanks for your help!

**Comment by scottamain** [comment]
Happy to hear it, thank you!
