### ISSUE TITLE
[BUG] `ref` args are not lowered to `ptr noalias`

### ISSUE THREAD

**Issue by soraros** [modularml/mojo#3544]
### Bug description

As title. CC. @lattner

**Comment by lattner** [comment]
I looked into this a bit (it is AKA MOCO-914), the problem is that we're lowering out information about whether a ref is mutable or not too early - we need to understand whether `ref` was declared immutable (in which case it was allowed to alias) or declared parametric mutable and instantiated on an immutable type (where it's not).

It'll take a bit of rejiggering to do this - the cleanest way to handle it seems to be splitting the internal Ref arg convention in the compiler into two enums.  I'll poke at this at some point.  Thank you for filing it!

**Comment by lattner** [comment]
I took a look at this, and we can do about half of this, but not perfectly right now.  When declaring a ref argument as taking a MutableLifetime, we can know that all instantiations will be no-alias, but when it has parametric mutability, we don't propagate the information through the compiler in the right way to maintain this.  I landed a fix to make it handle the obvious case well, which is the most important anyway.
