### ISSUE TITLE
[Feature Request] Introduce `alias Byte = UInt8`

### ISSUE THREAD

**Issue by soraros** [modularml/mojo#3634]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

As title.

### What is your motivation for this change?

It helps document the intent, especially in low-level code (e.g., `memcpy`), where we treat the underlying type as just a pack of bits rather than a numerical type, similar to the distinction between `i1` and `bool`.

We *could* introduce a nominal type `Byte` which implicitly converts to `UInt8`, but that feels more complex than necessary.

### Any other details?

N/A

**Comment by martinvuyk** [comment]
I think it's also important to note that in Python byte is it's own object type with it's own type of representation (prints with `b'{value_here}'`) and [many other byte related things](https://docs.python.org/3/library/stdtypes.html#binary-sequence-types-bytes-bytearray-memoryview).

Also, `Span[Uint8]` could be aliased to `ByteArray` and `List[UInt8]` to `Bytes` since their APIs are very similar to [byte operations](https://docs.python.org/3/library/stdtypes.html#bytes-and-bytearray-operations)

(btw typo in the title)

**Comment by JoeLoser** [comment]
Have you seen [https://github.com/modularml/mojo/pull/2096#issuecomment-2067515392](https://github.com/modularml/mojo/pull/2096#issuecomment-2067515392) and our feedback there?  I'd be open to someone adding a lightweight alias in the meantime to improve readability/express intent better at call sites.

**Comment by soraros** [comment]
> Have you seen [#2096 (comment)](https://github.com/modularml/mojo/pull/2096#issuecomment-2067515392) and our feedback there? 

Yea, I think `Bytes` needs way more justification and design.

> I'd be open to someone adding a lightweight alias in the meantime to improve readability/express intent better at call sites.

Let's move forward with simply `alias Byte = UInt8` then. I think it's a good first issue.

**Comment by JoeLoser** [comment]
Sounds good, just added "good first issue".  Whoever takes this, feel free to add the alias and we can incrementally apply it where we're working with "Bytes".
