### ISSUE TITLE
[Feature Request] Direct embedding into HTML without requiring a templating engine.

### ISSUE THREAD

**Issue by Dinesh6777** [modularml/mojo#3765]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

It would be awesome to have a built-in mechanism for Mojo to directly embedding Mojo code within HTML without needing a separate templating engine like jinja-flask engine.

In the below PHP example, the PHP code is embedded directly inside HTML. When the page is requested by a client, the server processes the PHP code, and the result is plain HTML sent to the browser. The browser never sees the PHP code itself; it only sees the output generated by PHP.

```
<?php for ($j = 1; $j <= 3; $j++): ?>
    <li>List item <?php echo $j; ?></li>
<?php endfor; ?>

```

### What is your motivation for this change?

To have python like syntax for direct embedding in HTML.

**Comment by martinvuyk** [comment]
I think this would be very hard to implement and maintain as a standard library. It would have it's own syntax and would practically be a mini-language within Mojo. IMO the closest thing we can expect from a standard library is format strings (which are already quite challenging to implement well). A templating engine is one of the things that IMO should be developed by the community, by people who know exactly what kind of features they'd like to see and what compromises they are willing to make.

PS: you actually gave me an interesting idea to make format string opening and closing characters (normally `{` and `}`) be able to be custom characters :thinking:. It would complicate the implementation even more but might allow people to develop things like this. Anyway, it will take a long time still since we don't even have format specifiers implemented yet.

**Comment by ematejska** [comment]
I have no idea how the PHP stuff works but from this documentation [https://www.php.net/manual/en/language.basic-syntax.phptags.php](https://www.php.net/manual/en/language.basic-syntax.phptags.php) it seems like this might happen at the parser level with special tags.   So perhaps this could be done at compilation time.<br>This is however, out of scope from our roadmap right now so I will close this.
