### ISSUE TITLE
[BUG] [LSP] Raw `StringLiteral` interpreted as `StringLiteral` in docstrings

### ISSUE THREAD

**Issue by martinvuyk** [modularml/mojo#3889]
### Bug description

Raw `StringLiteral` interpreted as `StringLiteral` in docstrings

### Steps to reproduce

```mojo
fn _some_function():
    """Summary.

    Examples:

    ```mojo
    print(r"\U0001f525")
    ```
    .
    """
    ...
```
error output: `invalid escape sequence`, which is an unrelated problem of unicode escape sequences not being accepted yet, but this should not happen since it's a raw string

### System information

```shell
- Provide version information for Mojo by pasting the output of `mojo -v`
`mojo 25.1.0.dev2024121405`
```

**Comment by walter-erquinigo** [comment]
The underlying issue is that the compiler doesn't want this kind of sequences in the docstring. <br>If you have this function:

```
fn _some_function():
    """Summary.

    Examples:

    print(r"\U0001f525")  # compiler complains here

    ```mojo
    print(r"\U0001f525")  # compiler complains here
    ```
    .
    """
    print(r"\U0001f525")  # all good here
```

You'll notice that the compiler will complain in the first occurrence of `print(r"…")`, which is actually the same as the second one because the codeblock within the "\`\`\`mojo" directive is still just the docstring. We present the codeblock in a cute way via the IDE, but it's still just a docstring for the compiler. I just tried relaxing the compiler to accept \\U sequences, but then the LSP that handles the codeblock gets super confused and I don't see a simple way to handle this.

Changing this behavior won't be trivial at all, as it would require teaching the compiler about actual codeblocks and I'd rather don't do that.

I'm sorry that I can't offer some workaround. This is hard corner case for the LSP.

**Comment by martinvuyk** [comment]
>  I just tried relaxing the compiler to accept \U sequences, but then the LSP that handles the codeblock gets super confused and I don't see a simple way to handle this.

@walter-erquinigo In this case the problem (I think) is that `r"` is not being correctly interpreted as a raw string literal, the escape sequence shouldn't be parsed, the characters are raw values. The escape sequence thing is another unrelated problem that the compiler currently doesn't support unicode escape sequences in string literals.

**Comment by walter-erquinigo** [comment]
Not really. What happens is that the LSP asks the compiler to provide the contents of the codeblock, but the compiler doesn't return what it should because it has seen the \\ char somewhere and escaped the contents.

**Comment by martinvuyk** [comment]
Ok if it can't be taught about codeblocks then I guess I'll just have to do `"print(r"\\U0001f525")"`. There are still some cornercases even with escaping, I'll open another issue
