### ISSUE TITLE
[Docs] Inconsistent name "programming-manual" in Playground notebooks

### ISSUE THREAD

**Issue by gryznar** [modularml/mojo#447]
### Where is the problem?

programming-manual.ipynb

### What can we do better?

![image](https://github.com/modularml/mojo/assets/90425096/e8e674f6-7880-4ba4-8c91-cdd0f33e5171)
As we can see other notebooks use PascalCase naming convention. It will look much better if all names will follow this semantic

**Comment by lattner** [comment]
@scottamain fyi

**Comment by scottamain** [comment]
Yes, the inconsistency is not ideal, but it's necessary that we keep it this way.

`programming-manual.ipynb` was originally written in markdown (`programming-manual.md`) just for the website, and all files on the website use this lower-case and hyphenated style. Only recently did we convert this to a notebook and make it available in Mojo Playground. Due to this legacy, I don't want to change the filename because that would break the existing [URL on the website](https://docs.modular.com/mojo/programming-manual.html). I also don't think there's any need to rename the file when we copy it to the Mojo Playground, just for appearances—that would remove the visible association with the file on the website, which is appropriate because they are the exact same file.

I actually think it's kind of nice that this file looks different in Mojo Playground, because it is, in principle, a very different type of notebook. All the others notebooks (in CamelCase) have a very specific purpose with a narrow scope for their code, whereas the Programming Manual is wide ranging and actually includes several blocks of non-executable code—it's primary purpose is to explain various Mojo features, but it's obviously a nice bonus that we can make many code examples executable if you read it in a Jupyter environment. :)
