### ISSUE TITLE
[Feature Request] Native Windows support

### ISSUE THREAD

**Issue by raman1383** [modularml/mojo#620]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

native support for windows.

when will it be available?

### What is your motivation for this change?

I use Windows

**Comment by jackos** [comment]
Hi @raman1383 we can leave this ticket open thanks, so people can upvote and we can gauge how much interest there is for it.

**Comment by visakha** [comment]
a lot of devs out there work in corporations, like Ford | Bank of America etc etc etc
they all use windows and lot of restrictions
so the SDK should be straight fwd with no baggage like 
A) Need for elevated permissions 
B) Need for admin permissions

it should be as simple as 
A) Download the binary as a zip file
B) Extract it
C) Change PATH variable
D) Start Using it

**Comment by cksiow** [comment]
I believe another turn around solution is support mojo build with --target-triple x86_64-w64-win32 so we can run the execution file in windows OS
Currently facing issue when build with this target-triple "mojo: error: Couldn't find msvc toolchain."

**Comment by gryznar** [comment]
Keep in mind, that the easiest may be to prepare Linux version. Mac has similar architecture, so it is going second. Windows differentiates the most, so it goes last

**Comment by santagada** [comment]
Or maybe open source it first and we help modular port it 😉

**Comment by Moosems** [comment]
> Or maybe open source it first and we help modular port it 😉

They're waiting till it becomes mature enough for this :).

**Comment by hexpayload** [comment]
well，i hope mojo running on my Windows10 system

**Comment by ArEnSc** [comment]
yeah I would like this to be supported on Native windows, theres a huge gap in the market that mojo can cover for AI inference, espcially in the games sector right now I know many devs trying to get code from python compiled down to c to run in their applications, that process is  huge pain point, if we can develop portable cross platform inference services / processes from modular that would be amazing

**Comment by Neltherion** [comment]
I'm starting to get the feeling that Windows is going to be a second-class citizen in the Mojo world. Another similar programming language that got the same treatment was Crystal: It also started supporting Linux right from the start and claimed that "Windows Support" is coming and yet years later, there's still no sign of a Windows version of Crystal.

In the first blog posts of Mojo each week, there was a report on how the Windows version was progressing but recently there hasn't been any news about the Windows version🙁

**Comment by liudonghua123** [comment]
> I'm starting to get the feeling that Windows is going to be a second-class citizen in the Mojo world. Another similar programming language that got the same treatment was Crystal: It also started supporting Linux right from the start and claimed that "Windows Support" is coming and yet years later, there's still no sign of a Windows version of Crystal.
> 
> In the first blog posts of Mojo each week, there was a report on how the Windows version was progressing but recently there hasn't been any news about the Windows version🙁

another similar project is bun.

**Comment by AlgorithmicKing** [comment]
+1

**Comment by Ibrahim758** [comment]
Windows is the most widely used system in the world It is used by 69 operating system users in the world . Despite this, Mojo 🔥 does not work on this system. It was supposed to support the Windows system first.

**Comment by bahia14** [comment]
I do agree with you.... Ibrahim758

**Comment by bozohi** [comment]
You're a genius ibrahim758

**Comment by jloveric** [comment]
Even though I don't often use Windows, a bunch of my coworkers do so I think this is important! I won't be able to write anything in mojo at work probably until it's in Windows!

**Comment by AlgorithmicKing** [comment]
> Windows is the most widely used system in the world . 69% of operating system users in the world use Windows . Despite this, Mojo 🔥 does not work on this system. It was supposed to support the Windows system first.

why is this marked as abuse?

**Comment by a62690705** [comment]
Maybe because someone was upset by this comment

**Comment by a62690705** [comment]
I am a professional game programmer. My team and I are working on creating a game engine supported by artificial intelligence, based mainly on Max. I hope that Mojo 🔥 and Max will be supported for the Windows operating system soon because this is a very important matter. For us

**Comment by a62690705** [comment]
If it succeeds and we finish the engine within the next six months, and the engine spreads and is adopted mainly in the game industry, the company will achieve... modular With profits amounting to tens of millions of dollars, I am thinking of naming the engine Laura. Anyway, we are working hard and diligently. I hope it will succeed because the future electronic games industry needs game engines supported by artificial intelligence.

**Comment by lucasjinreal** [comment]
Please support Windows.

**Comment by Moosems** [comment]
@lucasjinreal They have a lot of internal support as well, it will come in due time.

**Comment by lucasjinreal** [comment]
Thanks, I think should be a relatively higher priority. As mojo trends to attract more attention, the whole platform coverage should put on the agenda now.

**Comment by a62690705** [comment]
According to my simple information, perhaps Windows will be supported next year

**Comment by a62690705** [comment]
They don't care about Windows support this year

**Comment by Moosems** [comment]
@a62690705 Care to share your source? I highly doubt that they simply don't care about supporting Windows.

**Comment by a62690705** [comment]
When I post any comment regarding the Windows support date or anything related to Windows, they delete the comment and prevent me from writing again and block me. They blocked me more than 4 times because I talked about Windows. Windows will not be supported this year.

**Comment by lucasjinreal** [comment]
@a62690705 Holy shit, why did they do this? Does windows make them angry?

**Comment by Moosems** [comment]
Im skeptical to believe that because they don't generally block or delete posts. Unless you did something obscene I don't believe they would do that. Also why are you making four posts for them to block? Was it all at once cause that would be grounds for spam.

**Comment by a62690705** [comment]
You're just an idiot. I don't care if you believe it or not. You're just a stupid bitch. I don't care if you believe it or not. I'm talking about my experience in asking questions about Windows, and I don't care about you. You son of a bitch .This language is doomed to failure if it does not support Windows

**Comment by a62690705** [comment]
You defend them because you are their slave. Fuck you

**Comment by a62690705** [comment]
I was only asking respectful questions about Windows, and I was never asked an obscene question, but enough is enough, you are just stupid idiots. Fuck you.

**Comment by Moosems** [comment]
So *thats* why they deleted your comments. I was right :)

**Comment by Moosems** [comment]
I want Windows support as much as you do but that is *not* the way to be persuasive or convince others. Swearing and acting like a child doesn't do much in this setting. I don't want to have any beef with you but I'd prefer it if you didn't say such things.

**Comment by a62690705** [comment]
I was expecting this answer from you, not for this reason, but because they are not actually planning to support Windows this year, and when I used to open discussions about Windows, the employees would delete those discussions, not because they are full of insults, but rather they do not like to talk about Windows.

**Comment by Moosems** [comment]
Or maybe because they've been bombarded with hundreds of issues and discussions already?

**Comment by a62690705** [comment]
Fuck them, idiots. It was just a discussion about the future of Mojo without Windows support. Stupid bitches.

**Comment by a62690705** [comment]
What evidence are you talking about, idiot? Are you stupid? You said to delete the discussion permanently from GitHub

**Comment by a62690705** [comment]
You will remain stupid for the rest of your life because you trust people blindly and stupidly

**Comment by melodyogonna** [comment]
@a62690705 are you a bot? Why all the cussing on a public Github repo, with an account with very little activity? Smells like troll behaviour to me, which also explains your posts being deleted (if they were indeed deleted)

**Comment by hogepodge** [comment]
Stepping into this conversation. @a62690705 has been banned multiple times for violating the code of conduct for the Modular community. This has included

- trolling by repeatedly asking the same question over and over
- verbally abusing Modular staff and community members
- evading prior bans by creating new accounts

I'm locking this issue until things cool off.

We want to create a welcoming and safe space for everyone, and we also want to hear community feedback about what's important to them. We also have very limited resources as we build out Mojo and MAX, and may not be able to deliver on every request as quickly as people would like.

**Comment by xmaxrayx** [comment]
please do this I hate linux and I don't want use it with my laptop, WSL may work but it's not good if you want best hardware performance

**Comment by AlgorithmicKing** [comment]
I don't know why they are doing this. they released max 24.2 and everything else but not mojo for windows

**Comment by Neltherion** [comment]
It seems Mac and everything else has more priority for them than Windows😒

**Comment by melodyogonna** [comment]
It's straightforward. The team does not have any extra engineering bandwidth to dedicate to keeping a Windows version up to date with the changes being made. Linux (just Ubuntu) has first-class support because it's important for open source and deployment, Mac M-series because that is the system everyone at Modular uses.

**Comment by Neltherion** [comment]
> It's straightforward. The team does not have any extra engineering bandwidth to dedicate to keeping a Windows version up to date with the changes being made. Linux (just Ubuntu) has first-class support because it's important for open source and deployment, Mac M-series because that is the system everyone at Modular uses.

This is exactly why Windows may be considered a second-class citizen for Mojo throughout its lifetime. This approach to having Windows as a second-class citizen reminds me of the Crystal Language (No Windows support even after 9 years) and is unfortunately starting to turn my focus from Mojo to other alternatives (even Cython)😔

**Comment by melodyogonna** [comment]
> > It's straightforward. The team does not have any extra engineering bandwidth to dedicate to keeping a Windows version up to date with the changes being made. Linux (just Ubuntu) has first-class support because it's important for open source and deployment, Mac M-series because that is the system everyone at Modular uses.
> 
> This is exactly why Windows may be considered a second-class citizen for Mojo throughout its lifetime. This approach to having Windows as a second-class citizen reminds me of the Crystal Language (No Windows support even after 9 years) and is unfortunately starting to turn my focus from Mojo to other alternatives (even Cython)😔

Not really true.  it’s a common misconception that most open source projects are cross-platform from the start. Most open source projects start out supporting just the machine that the developer is working with. Eventually, it’s ported by the community to other platforms. Mojo doesn’t support Windows yet because it’s not completely open source. Once the compiler gets open-sourced, I expect the community to port it to other platforms. Once it gets there, I expect a core maintainer to work on its upkeep.

**Comment by itcd** [comment]
> I'm starting to get the feeling that Windows is going to be a second-class citizen in the Mojo world. Another similar programming language that got the same treatment was Crystal: It also started supporting Linux right from the start and claimed that "Windows Support" is coming and yet years later, there's still no sign of a Windows version of Crystal.
> 
> In the first blog posts of Mojo each week, there was a report on how the Windows version was progressing but recently there hasn't been any news about the Windows version🙁

Mojo still lacks native Windows support after about a year. :(

> > It's straightforward. The team does not have any extra engineering bandwidth to dedicate to keeping a Windows version up to date with the changes being made. Linux (just Ubuntu) has first-class support because it's important for open source and deployment, Mac M-series because that is the system everyone at Modular uses.
> 
> This is exactly why Windows may be considered a second-class citizen for Mojo throughout its lifetime. This approach to having Windows as a second-class citizen reminds me of the Crystal Language (No Windows support even after 9 years) and is unfortunately starting to turn my focus from Mojo to other alternatives (even Cython)😔

Mojo still lacks native Windows support after about a year. :(

**Comment by itcd** [comment]
The outlook is concerning as Mojo continues to lack native Windows support, nearly a year later. :(

**Comment by AlgorithmicKing** [comment]
looks like mojo is not the game changer for 72% (Windows users) of worlds Computer users

**Comment by Moosems** [comment]
You guys know the world doesn’t revolve around you and windows right?

**Comment by Neltherion** [comment]
Any progress on Windows support lately? Modular Blog used to announce the progress on Windows every week but recently there's been a blackout on Windows progress news😒

**Comment by AlgorithmicKing** [comment]
> You guys know the world doesn’t revolve around you and windows right?
Of course, the world doesn't revolve around us or Windows. However, considering Windows powers over 72% of the world's desktop computers and is integral to countless businesses, educational institutions, and personal users globally, it undeniably plays a crucial role in how people interact with technology and conduct their daily activities. Understanding its importance and addressing issues related to it is not about self-centeredness; it's about recognizing and engaging with a significant component of modern digital infrastructure.

**Comment by AlgorithmicKing** [comment]
Of course, the world doesn't revolve around us or Windows. However, considering Windows powers over 72% of the world's desktop computers and is integral to countless businesses, educational institutions, and personal users globally, it undeniably plays a crucial role in how people interact with technology and conduct their daily activities. Understanding its importance and addressing issues related to it is not about self-centeredness; it's about recognizing and engaging with a significant component of modern digital infrastructure.

**Comment by jackos** [comment]
Hi all please don't attack each other over this, we understand how important the native Windows experience is for a large percentage of the world. The reason we haven't done this yet is purely due to limited engineering hours, and we need to focus on priorities such as GPU support to create a compelling product. We care about Windows, as you can see when we add stdlib functionality we include native Windows compatible code and tests. When we have the engineering hours available we'll do it.

Please be respectful with each other.

**Comment by bahia14** [comment]
@Algorithm King, totally agree !!!

**Comment by Neltherion** [comment]
@jackos
Thanks for the clarification. Just please make sure to assign at least one person to it or else it will turn into the Crystal Lang conundrum over Windows support (after 9 years, Crystal Lang team is still "looking" for engineers for Windows support and the language still doesn't have a stable Windows release).

**Comment by melodyogonna** [comment]
GPU support is nearing completion, at least for Nvidia GPUs. So maybe the team might be able to free up some engineering bandwidth for Windows, assuming there isn't another high priority max functionality.

**Comment by walter-erquinigo** [comment]
Indeed, our priorities right now are GPU support and satisfying the needs of the market. We know that Windows is important and it's included in the roadmap. As you may imagine, there's a good portion of the market using Windows, especially not in the US.

However, at this point I can't share details about timelines.

**Comment by xmaxrayx** [comment]
Test from my email

**Comment by bahia14** [comment]
Hi


By the statcounter (link below), we have:


1. Desktop Operating System Market Share in United States Of America - June
2024

Windows has 62.4%
OS X 24.7%

Where Windows is 2.5x bigger than OS X

https://gs.statcounter.com/os-market-share/desktop/united-states-of-america



2. the Desktop Operating System Market Share Worldwide - June 2024

Windows has 72.9%
OS X 14.9%

Where Windows is 4.9x bigger than OS X


https://gs.statcounter.com/os-market-share/desktop/worldwide


I could not understand why Modular didn't start the project with Windows.

**Comment by bahia14** [comment]
I see.
By the business point of view, you have to look what is more lucrative....

**Comment by walter-erquinigo** [comment]
Indeed. The lucrative part is important. We are a startup, so we just don't exist without entering the part of the market that could benefit from our products. This is basically Linux for AI servers. Mac was a relative easy port, as mentioned above, because it's posix and is very similar to Linux.

Windows will come, but we are focusing now on GPU for Linux specifically.

**Comment by xmaxrayx** [comment]
The issue is most local AI on individual hardware are limited to low vram
not on speed most AI script that written on python are warped to Cuda so
speed not that big issue.

so understandable MOJO will care about people who actually use their
product aka Linux server users, mac is based on Unix and doesn't have that
variaty on hardware, so it's not hard.


Windows in other hand defferent system, defferent hardware and let's not
forget the new thing Arm windows and npu and good luck with snapdragon
documentation (as I heard) , so it's not that easy we will be lucky if they
did it in 1 year, let's not forget not all windows user devs or care about
AI.


1 second saved in individual user machine not the same as saving 1 second
on server machine.

**Comment by droy-proxsys** [comment]
Just keeping this train chugging along... So, like many poor souls, I work in a company that chains me to Windows (ugh, I know, right?). I really want to dive into this language more, and while I'm not launching major AI models into the stratosphere, we do have some heavy ML use cases. Enter Mojo – potentially a game changer!

Yeah, I get it – Windows is the bane of my existence and probably yours too. But hey, for all of us trapped in this Windows wonderland, can we get a ballpark figure on when Mojo might grace us with its presence? We'd really appreciate it, or at least I would, because I’m dying a little inside every day waiting for this to be openly available.

**Comment by qq-me** [comment]
WSL would work fine, I just wish I could run WSL mojo from normal VSCode instead of having to open separate VSCode in WSL and navigate to my windows files through the scary looking linux filesystem, but that is VSCode related problem

**Comment by Jabadahut50** [comment]
> I believe another turn around solution is support mojo build with --target-triple x86_64-w64-win32 so we can run the execution file in windows OS Currently facing issue when build with this target-triple "mojo: error: Couldn't find msvc toolchain."

Honestly this would be the best stop gap. Being able to at least compile exe's for windows is enough for my purposes and I'm sure for a lot of others as well. Not that native windows support shouldn't come down the road, but at a bare minimum getting exe compilation would allow open source users to start publishing cool projects for windows.

**Comment by walter-erquinigo** [comment]
There's been a lot of activity here, and I can empathize with most of the opinions in this thread, however, I'll be closing this issue for the time being because we don't have Windows in the short term roadmap. We are still committed to bringing Mojo and MAX to Windows when it's the right moment for the company. That day we can reopen this issue and have a more concrete discussion.

**Comment by GameCodeMode** [comment]
any specific month so that i can prepare for it?

**Comment by Moosems** [comment]
@GameCodeMode "we don't have Windows in the short term roadmap"

**Comment by Neltherion** [comment]
"Second Hand Citizen"🫠

**Comment by Neltherion** [comment]
7 Months have passed since we last asked when the Windows version will come. In the meantime MAX has had several releases and coverage.

Are we there yet? When is the Windows version going to be released?

**Comment by GameCodeMode** [comment]
the only reason why mojo is not being talked about is because it doesn't have windows support

**Comment by lucasjinreal** [comment]
> the only reason why mojo is not being talked about is because it doesn't have windows support

Using Rust,

**Comment by Marcus-Peterson** [comment]
> [@GameCodeMode](https://github.com/GameCodeMode) "we don't have Windows in the short term roadmap"

Then your roadmap may be flawed. Isn't your goal that Mojo should be a staple in the industry, not a replacement for python necessarily. But widely used? Like I would LOVE the day I can pitch using Mojo to my team. But alas... Everyone would look at me like I'm a fool because Mojo isn't supported on Windows. Yes I get it, you guys at Modular want to make Mojo the best it can be. And I applaud you for it. 
But could you at least put out a statement or something regarding Windows? Anything? You say in the **short term**. But what is the **long term**? Why are you guys skipping Windows entirely when you know that majority of the world is using Windows compared to Linux?

**Comment by visakha** [comment]
Good points Marcus

I think Modular should partner with Microsoft and get it done, if they are
understaffed.
Most companies provide Windows laptop to their employees and contractors, I
wonder why Modular wants to ignore this fact

**Comment by Neltherion** [comment]
The sheer focus on DLAs and accelerating AI workloads has blinded them. Mojo seems to be just a tool to push MAX and I'm not sure how much the industry has adopted Mojo+Max recently but the byproduct is that anything which isn't Linux and Server-related has completely lost focus for them.

**Comment by dlroy88osu** [comment]
As a data engineer I would love to be able to use this, but in my current place of employment they have wsl & vm's locked... Plus they only issue windows computers. I have a huge need for a language that could be as data oriented and compiled and tooling built in for ml/gpu tasks... 

I understand making it great, but you are cutting off the largest section of people that would use and expand the language. It sucks, because if it keeps going down this road your going to turn into something like nim... had loads of potential, but couldn't quite pull it into the main stream... so there it sits as an overpowered hobby language with mostly dead libs...

**Comment by melund** [comment]
I love the new Mojo feature of calling Mojo from Python:
https://docs.modular.com/mojo/manual/python/mojo-from-python/

I would love to integrate the feature in my libraries to speed things up. But since my libraries are cross-platform mojo support for windows is needed before I can really use that feature.

**Comment by MosGeo** [comment]
With the ability to call mojo from python, I would love to start integrating some mojo functions in my python windows desktop application. This is only possible with native windows support.

**Comment by Neltherion** [comment]
Here to remind everyone that Mojo just raised 250 million dollars and I hope a small part of it would be assigned to finally release the Windows support🙂

**Comment by GodGavin** [comment]
really  want Windows support
Can't agree more

**Comment by GodGavin** [comment]
> 在这里提醒大家，Mojo 刚刚筹集了 250.<> 亿美元，我希望其中的一小部分能够用于最终发布 Windows 支持🙂

really？hope they will

**Comment by Algorithm** [comment]
Remove @algorithm reference from your code please. It copies my account in.On 12 Nov 2025, at 04:20, GavinGao ***@***.***> wrote:﻿GodGavin left a comment (modular/modular#620)
really  want Windows support
Can't agree more

**Comment by GodGavin** [comment]
> Remove [@Algorithm](https://github.com/Algorithm) reference from your code please. It copies my account in.On 12 Nov 2025, at 04:20, GavinGao ***@***.***> wrote:﻿GodGavin left a comment ([modular/modular#620](https://github.com/modular/modular/issues/620))
> really  want Windows support
> Can't agree more
> 
> —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

what do u mean？

**Comment by Marcus-Peterson** [comment]
> mean？

Bot behavior, ignore it

**Comment by leotorrez** [comment]
Has there been any progress or discussions on the topic? It seems like the most popular OS being supported would be important for mojo

**Comment by skiddude** [comment]
[Mojo 1.0 released](https://www.modular.com/blog/modular-26-5-mojo-1-0-is-here), and we still do not have support for Windows :(

**Comment by Neltherion** [comment]
wInDoWs SuPpOrT iS nOt ThE pRiOrItY! oUr StAfF HaVe EiThEr MaC oR lInUx! 🧽😤

**Comment by stimpy77** [comment]
At this point someone could probably fork it and throw Opus 5 / gpt-5.6-sol at it and get Windows support up without a lot of time or effort. I can't imagine there'd be much in code design to deal with. A major corp could throw $1k at it and have it done in a week. 
Maybe not. I haven't looked at the codebase.

**Comment by Pixel-Minions** [comment]
Honestly, a big reason to use Mojo was the promise of getting Rust-like performance with Python-like syntax. But LLMs now solve a lot of what many people (including me) needed Mojo for in the first place. I can just ask for a tool to be written in Rust and get something that works, without needing to learn or adopt another language. That makes Mojo’s value proposition a lot less compelling for me.

**Comment by skiddude** [comment]
> At this point someone could probably fork it and throw Opus 5 / gpt-5.6-sol at it

Here is the thing... Mojo's compiler isn't open source yet

**Comment by dzmitry-lahoda** [comment]
> Native Windows support is coming to Mojo, thanks to a collaboration with the Microsoft Windows team.

from https://www.modular.com/blog/modcon-announcements

**Comment by droy-proxsys** [comment]
> > Native Windows support is coming to Mojo, thanks to a collaboration with the Microsoft Windows team.
> 
> from https://www.modular.com/blog/modcon-announcements

Oh god... Microslop's gonna slop it up! My hope for something good is now dwindling...

**Comment by Marcus-Peterson** [comment]
> > Native Windows support is coming to Mojo, thanks to a collaboration with the Microsoft Windows team.
> 
> from https://www.modular.com/blog/modcon-announcements

About time I guess. Good for them, Modular is heading in the right direction with this. Even though it is Microsoft.. I think to be fair, having Microsoft engineers helping build the Windows native version is a benefit. As long as they don't turn it into some sloppified version.. Which you know.. Is a risk whenever Microsoft get their hands on something. But we should be optimistic guys. This is good news
