### ISSUE TITLE
[Modular CLI]: modular install mojo  error: externally-managed-environment

### ISSUE THREAD

**Issue by fox5352** [modularml/mojo#683]
### Issue description

I followed the linux installation guide on the webpage 

Install the Modular CLI:
```
sudo curl https://get.modular.com | \ MODULAR_AUTH=mut_210c82e4926849f6addab7c1a42e0258 \ sh -
```
Install the Mojo SDK:
```
modular install mojo
```
⬆ This is where the error happens ⬆

I've done **modular clean** an tried again and got the same problem

### Steps to reproduce

```
modular install mojo
# Found release for https://packages.modular.com/mojo @ 0.2.1, installing to /home/christopher/.modular/pkg/packages.modular.com_mojo
# Downloads complete, setting configs...
# Configs complete, running post-install hooks...
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.11/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specif
```

### Version Info

```shell
- Provide Modular CLI version by pasting the output of `modular -v`
  modular 0.1.4 (6b54d308)

- What OS did you install modular CLI on ?
  distro: Ubuntu 
  version: 23.04 
  cpu: i5 2400
  arch: x86_64
  ram: 12GB
```

**Comment by ZSmain** [comment]
I got the same Issue on my machine:

`Modular CLI version: modular 0.1.4 (6b54d308)
OS:
    -Distro: Debian
    -version: 12
    -codename: trixie
    -arch: x86_64`

**Comment by maciej23** [comment]
I got the same issue on Ubuntu 23.04, modular 0.1.4 (6b54d308). Looks like there are a couple of workarounds.

One is moving the `/usr/lib/python3.11/EXTERNALLY-MANAGED` file:
```
sudo mv /usr/lib/python3.11/EXTERNALLY-MANAGED /usr/lib/python3.11/EXTERNALLY-MANAGED.bak
```

Another workaround is setting the `break-system-packages` option in `~/.config/pip/pip.conf`:
```
[global]
break-system-packages = true
```

Be careful: by doing this you are allowing pip to install system-wide packages, which could lead to your system breaking (although it looks like modular is installing them in the user packages in `~/.local/lib/python3.11/site-packages/`, not the system packages, which should have less severe consequences).

A safer option, if you're using VSCode, is to use Dev Containers, and install mojo in the container instead of your system.

**Comment by bzcheeseman** [comment]
This will be fixed in a future release, in the meantime please follow @jackos advice above.
