### ISSUE TITLE
Matmul.pynb shows error in SIMD code , Parallelizing and Tiling code demos in playground.

### ISSUE THREAD

**Issue by jwgomez** [modularml/mojo#913]
### Bug description

The below error occurs. The same error occurs for  SIMD code , Parallelizing and Tiling code.
![image](https://github.com/modularml/mojo/assets/145900441/5042bc0b-0e0b-45b1-a1fe-d6f79379f046)

It works till 13.
![image](https://github.com/modularml/mojo/assets/145900441/8ee47786-66ab-41fc-ab45-7c1c2f960aee)

Please review.

### Steps to reproduce

- Include relevant code snippet or link to code that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- If using the Playground, name the pre-existing notebook that failed and the steps that led to failure.
- Include anything else that might help us debug the issue.

### System information

```shell
Tried on Windows 10 and 11 in Modular Playground.
```

**Comment by gujuriu** [comment]
Hi @jwgomez, few hours after they released mojo v0.3.0 they updated also some of the examples from [this repo](https://github.com/modularml/mojo/commits/main) check commits from Sept 21, 2023, if you do a `git pull` in order to get the latest code you will be able to run again the code.

Keep in mind that you might encounter other ~issue reported [here](https://github.com/modularml/mojo/issues/904), if you encounter that, my advice is to switch to Mojo 🔥 VSCode extension v0.2.1 (from VSCode Extensions, search for Mojo, click on dropdown from Uninstall, choose `Install Another Version...`, choose 0.2.1).

**Comment by ematejska** [comment]
Did you get a chance to try the updated notebooks?

**Comment by jackos** [comment]
See @ematejska comment above for the workaround.

Resolved in next release thanks.
